### Hyperparameter Tuning using Optuna

In [1]:
# Import necessary libraries
import optuna
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

c:\Users\LOQ\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

#### Load the Pima Indian Diabetes dataset from sklearn.
#### Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
#### We will load the actual diabetes dataset from an external source

In [2]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Input the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split data into features
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into train, test -> split (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler()) # We aim to maximize accuracy
study.optimize(objective, n_trials=50) # Run 50 trials to find best hyperparameters

[I 2026-08-19 15:56:58,366] A new study created in memory with name: no-name-280cc0a5-3545-40be-8719-0fcc111aa850
[I 2026-08-19 15:56:59,911] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 17}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-19 15:57:00,813] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 9}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-19 15:57:02,906] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 197, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:03,998] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 107, 'max_depth': 6}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:05,578] Trial 4 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 146, 'max_depth': 9}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:07,069] Trial 5 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 13}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:08,860] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 174, 'max_depth': 5}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:10,231] Trial 7 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 140, 'max_depth': 4}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:11,394] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 120, 'max_depth': 4}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:12,138] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 70, 'max_depth': 9}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:14,298] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 194, 'max_depth': 19}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:16,403] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 20}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 15:57:18,528] Trial 12 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 197, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:20,425] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 176, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:22,308] Trial 14 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 180, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:24,355] Trial 15 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 198, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:25,905] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:27,936] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 12}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:29,699] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:30,340] Trial 19 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 58, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:31,993] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 157, 'max_depth': 11}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:34,043] Trial 21 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 198, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:35,997] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:38,031] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:39,866] Trial 24 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 186, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:41,657] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 183, 'max_depth': 20}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:43,446] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 189, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:45,190] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 169, 'max_depth': 13}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:46,635] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 151, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:48,018] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 165, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:49,442] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 189, 'max_depth': 11}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:50,846] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 189, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:52,158] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:53,667] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:54,340] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:55,919] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:57,387] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 173, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:57:58,600] Trial 37 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 153, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:00,021] Trial 38 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 184, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:01,048] Trial 39 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:02,462] Trial 40 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:03,384] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 16}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:04,452] Trial 42 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:05,314] Trial 43 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:06,116] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 93, 'max_depth': 18}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:07,185] Trial 45 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 121, 'max_depth': 14}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:08,649] Trial 46 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 193, 'max_depth': 8}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:09,248] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 17}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:10,434] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 19}. Best is trial 12 with value: 0.7802607076350093.
[I 2026-08-19 15:58:11,390] Trial 49 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 15}. Best is trial 12 with value: 0.7802607076350093.

In [7]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 197, 'max_depth': 16}

In [8]:
from sklearn.metrics import accuracy_score
# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### Samplers in Optuna

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [13]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-08-19 16:08:54,169] A new study created in memory with name: no-name-04a91b85-0601-4884-a800-bd797a1e4e63
[I 2026-08-19 16:08:54,975] Trial 0 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 103, 'max_depth': 3}. Best is trial 0 with value: 0.7560521415270017.
[I 2026-08-19 16:08:55,830] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 19}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-08-19 16:08:56,408] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 71, 'max_depth': 16}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:08:57,147] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 92, 'max_depth': 5}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:08:57,667] Trial 4 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 64, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:08:58,536] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 17}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:09:00,106] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 185, 'max_depth': 20}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:09:00,550] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 56, 'max_depth': 13}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:09:01,088] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 59, 'max_depth': 13}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:09:02,085] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 113, 'max_depth': 9}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-08-19 16:09:03,068] Trial 10 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:04,275] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 137, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:05,207] Trial 12 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 117, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:06,228] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 131, 'max_depth': 6}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:06,877] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 79, 'max_depth': 19}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:07,730] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 10}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:08,580] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 18}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:09,224] Trial 17 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 85, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:10,499] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 161, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:11,184] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 88, 'max_depth': 18}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:12,839] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 17}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:14,212] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 158, 'max_depth': 11}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:15,412] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 14}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:15,982] Trial 23 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 6}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:16,871] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 111, 'max_depth': 5}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:17,293] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:18,062] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 20}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:19,232] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 137, 'max_depth': 16}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:20,560] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 169, 'max_depth': 12}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:21,236] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 82, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:22,314] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 6}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:23,845] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 18}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:25,298] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 188, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:26,818] Trial 33 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 191, 'max_depth': 3}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:27,426] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 69, 'max_depth': 9}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:29,057] Trial 35 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 12}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:29,872] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 111, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:30,555] Trial 37 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:31,698] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 128, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:32,190] Trial 39 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:33,395] Trial 40 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 20}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:34,634] Trial 41 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 146, 'max_depth': 4}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:35,287] Trial 42 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:36,439] Trial 43 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 151, 'max_depth': 9}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:37,194] Trial 44 finished with value: 0.756052141527002 and parameters: {'n_estimators': 91, 'max_depth': 3}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:37,754] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 13}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:38,699] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 119, 'max_depth': 8}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:39,318] Trial 47 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 84, 'max_depth': 19}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:40,299] Trial 48 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 15}. Best is trial 10 with value: 0.7802607076350093.
[I 2026-08-19 16:09:40,741] Trial 49 finished with value: 0.750465549348231 and parameters: {'n_estimators': 63, 'max_depth': 3}. Best is trial 10 with value: 0.7802607076350093.

In [14]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 118, 'max_depth': 16}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [16]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth' : [5, 10, 15, 20]
}

In [11]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-08-19 16:05:11,392] A new study created in memory with name: no-name-4d032b32-d87d-4ab1-883e-4b1576680aaf
[I 2026-08-19 16:05:12,251] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-19 16:05:13,380] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-19 16:05:13,765] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:14,514] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:15,289] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:15,687] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:16,804] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:17,933] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:19,076] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:20,569] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:22,228] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:23,736] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:25,186] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-19 16:05:25,595] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-19 16:05:26,471] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-19 16:05:26,887] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [17]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 118, 'max_depth': 16}

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### Optuna Visualizations

In [19]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

# 1. Optimization History
plot_optimization_history(study).show()

In [20]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [21]:
# 3. Slice Plot
plot_slice(study).show()

In [23]:
# 4. Contour Plot
plot_contour(study).show()

In [24]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

### Optimize Multiple ML Models

In [25]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [26]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [27]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-08-19 16:51:47,750] A new study created in memory with name: no-name-f62f3118-e160-4894-80ab-f90a5c8b7a73
[I 2026-08-19 16:51:48,773] Trial 0 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 261, 'learning_rate': 0.09064294754215058, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7430167597765364.
[I 2026-08-19 16:51:49,069] Trial 1 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 56, 'learning_rate': 0.06946333245978126, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.7616387337057727.
[I 2026-08-19 16:51:49,094] Trial 2 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.2340646417505863, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7616387337057727.
[I 2026-08-19 16:51:50,344] Trial 3 finished with value: 0.7337057728119181 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 101, 'learning_rate': 0.02583612129830061, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7616387337057727.
[I 2026-08-19 16:51:51,196] Trial 4 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 237, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 1 with value: 0.7616387337057727.
[I 2026-08-19 16:51:51,588] Trial 5 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 134, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:52,125] Trial 6 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 137, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:52,865] Trial 7 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 234, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:56,762] Trial 8 finished with value: 0.7225325884543762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 278, 'learning_rate': 0.029782939028483443, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:57,640] Trial 9 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 276, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:57,674] Trial 10 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 68.34831138567972, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:58,207] Trial 11 finished with value: 0.750465549348231 and parameters: {'classifier': 'RandomForest', 'n_estimators': 190, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:58,975] Trial 12 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 190, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:51:59,671] Trial 13 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 178, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:00,235] Trial 14 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 163, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:00,658] Trial 15 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 110, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:00,691] Trial 16 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2246154910998281, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:01,503] Trial 17 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 211, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:02,122] Trial 18 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 146, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.7821229050279329.
[I 2026-08-19 16:52:02,266] Trial 19 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 69.66458657668352, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:02,458] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 81.19826053717367, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:02,699] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.20508708678084, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:02,883] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.15176811461933, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:02,993] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 47.15152934604954, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,058] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.8898142309629, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,111] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.14170823372996, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,201] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.962517938523003, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,420] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.51444987151103, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,495] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 26.25618768304183, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,515] Trial 29 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 4.398170495902938, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,547] Trial 30 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 36.28907139750116, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,736] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 91.71945393565183, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:03,924] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 88.16907956383653, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:04,043] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 44.624445258599515, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:04,339] Trial 34 finished with value: 0.7411545623836125 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 52, 'learning_rate': 0.011654168518092112, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:04,425] Trial 35 finished with value: 0.6741154562383613 and parameters: {'classifier': 'SVM', 'C': 99.39664156363858, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:04,466] Trial 36 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.899433437173627, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:05,056] Trial 37 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 90, 'learning_rate': 0.25682968543529844, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:05,153] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 40.35621209653578, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:05,291] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 49.41528008442364, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:05,799] Trial 40 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 74, 'learning_rate': 0.2822601091095767, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:05,904] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 47.10396277898208, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,022] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 50.525202961619605, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,156] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 58.72247478989383, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,240] Trial 44 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 26.789094205346128, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,409] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 64.0975429823254, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,433] Trial 46 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 32.33692752878967, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:06,528] Trial 47 finished with value: 0.6741154562383613 and parameters: {'classifier': 'SVM', 'C': 98.0226443343823, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,178] Trial 48 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 297, 'learning_rate': 0.010950643859835863, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,207] Trial 49 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 11.27403421113193, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,349] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 59.83401718439707, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,407] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 17.94077345111382, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,433] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.095374137499502, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,460] Trial 53 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 6.936264285133035, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,519] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.146462965114413, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 19 with value: 0.7858472998137801.
[I 2026-08-19 16:52:08,538] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3035802977264489, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:08,565] Trial 56 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2800599777281047, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:08,586] Trial 57 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6451544339372832, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:08,609] Trial 58 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.12784907751459623, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,278] Trial 59 finished with value: 0.7225325884543762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 219, 'learning_rate': 0.12590741843359937, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,298] Trial 60 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5872027268195686, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,320] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6623189821014768, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,340] Trial 62 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7573567785427309, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,362] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6730712593921362, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,383] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7381838045373152, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,842] Trial 65 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 123, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,869] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.9023830691499656, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,895] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8275470301087354, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,917] Trial 68 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5054689635251052, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,945] Trial 69 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.3189786847229106, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,974] Trial 70 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4878132052335495, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:10,997] Trial 71 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.6660076655924327, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,022] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8995564296240719, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,044] Trial 73 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.35093299335186623, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,066] Trial 74 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9411107578885359, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,683] Trial 75 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 162, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,708] Trial 76 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.711251665973752, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,730] Trial 77 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 0.3800250579538208, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,755] Trial 78 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 0.8404607956632806, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,781] Trial 79 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.9975156812968147, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.
[I 2026-08-19 16:52:11,800] Trial 80 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.48001037202800845, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 55 with value: 0.7858472998137803.

In [28]:
# Retrieve best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11434321309439659, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [29]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.743017,2026-08-19 16:51:47.752824,2026-08-19 16:51:48.773802,0 days 00:00:01.020978,NaN,NaN,GradientBoosting,NaN,NaN,0.090643,5.0,10.0,8.0,261.0,COMPLETE
1,1,0.761639,2026-08-19 16:51:48.774535,2026-08-19 16:51:49.069513,0 days 00:00:00.294978,NaN,NaN,GradientBoosting,NaN,NaN,0.069463,10.0,10.0,8.0,56.0,COMPLETE
2,2,0.728119,2026-08-19 16:51:49.070268,2026-08-19 16:51:49.094429,0 days 00:00:00.024161,1.234065,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.733706,2026-08-19 16:51:49.095227,2026-08-19 16:51:50.344609,0 days 00:00:01.249382,NaN,NaN,GradientBoosting,NaN,NaN,0.025836,15.0,2.0,3.0,101.0,COMPLETE
4,4,0.761639,2026-08-19 16:51:50.345258,2026-08-19 16:51:51.196097,0 days 00:00:00.850839,NaN,True,RandomForest,NaN,NaN,NaN,14.0,8.0,5.0,237.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2026-08-19 16:52:13.567582,2026-08-19 16:52:13.588580,0 days 00:00:00.020998,0.114343,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.787709,2026-08-19 16:52:13.589402,2026-08-19 16:52:13.610595,0 days 00:00:00.021193,0.108248,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2026-08-19 16:52:13.611348,2026-08-19 16:52:13.631705,0 days 00:00:00.020357,0.131829,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.787709,2026-08-19 16:52:13.632564,2026-08-19 16:52:13.652878,0 days 00:00:00.020314,0.106367,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.743017,2026-08-19 16:52:13.653634,2026-08-19 16:52:15.372465,0 days 00:00:01.718831,NaN,NaN,GradientBoosting,NaN,NaN,0.146859,13.0,5.0,4.0,300.0,COMPLETE

In [30]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 74
RandomForest        15
GradientBoosting    11
Name: count, dtype: int64

In [32]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.744202
RandomForest        0.765984
SVM                 0.774674
Name: value, dtype: float64

In [34]:
# Optimization History
plot_optimization_history(study).show()

In [35]:
# Slice Plot
plot_slice(study).show()

In [36]:
# Hyperparameter Importance
plot_param_importances(study).show()

In [38]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-08-19 16:57:33,895] A new study created in memory with name: no-name-4c622a12-ed47-4a0f-97b8-7350b1525bcc

[0]	train-mlogloss:0.82589	eval-mlogloss:0.81242
[1]	train-mlogloss:0.64488	eval-mlogloss:0.62879
[2]	train-mlogloss:0.51520	eval-mlogloss:0.48789
[3]	train-mlogloss:0.42262	eval-mlogloss:0.39107
[4]	train-mlogloss:0.34923	eval-mlogloss:0.31431
[5]	train-mlogloss:0.29416	eval-mlogloss:0.25632
[6]	train-mlogloss:0.25027	eval-mlogloss:0.20701
[7]	train-mlogloss:0.22797	eval-mlogloss:0.18424
[8]	train-mlogloss:0.19996	eval-mlogloss:0.15674
[9]	train-mlogloss:0.17965	eval-mlogloss:0.13135
[10]	train-mlogloss:0.16801	eval-mlogloss:0.11718
[11]	train-mlogloss:0.15751	eval-mlogloss:0.10397
[12]	train-mlogloss:0.15016	eval-mlogloss:0.09524
[13]	train-mlogloss:0.14655	eval-mlogloss:0.09111
[14]	train-mlogloss:0.14597	eval-mlogloss:0.09078
[15]	train-mlogloss:0.14205	eval-mlogloss:0.08547
[16]	train-mlogloss:0.13861	eval-mlogloss:0.08013
[17]	train-mlogloss:0.13658	eval-mlogloss:0.07741
[18]	train-mlogloss:0.13548	eval-mlogloss:0.07616
[19]	train-mlogloss:0.13500	eval-mlogloss:0.07496
[20]	train-mlogloss:0.13377	eval-mlogloss:0.07303
[21]	train-mlogloss:0.13243	eval-mlogloss:0.07371
[22]	train-mlogloss:0.13239	eval-mlogloss:0.07375
[23]	train-mlogloss:0.13246	eval-mlogloss:0.07370
[24]	train-mlogloss:0.13240	eval-mlogloss:0.07373
[25]	train-mlogloss:0.13237	eval-mlogloss:0.07376
[26]	train-mlogloss:0.13112	eval-mlogloss:0.07166
[27]	train-mlogloss:0.13092	eval-mlogloss:0.07109
[28]	train-mlogloss:0.12991	eval-mlogloss:0.06910
[29]	train-mlogloss:0.12995	eval-mlogloss:0.06907
[30]	train-mlogloss:0.12995	eval-mlogloss:0.06914
[31]	train-mlogloss:0.12992	eval-mlogloss:0.06918
[32]	train-mlogloss:0.12989	eval-mlogloss:0.06919
[33]	train-mlogloss:0.13002	eval-mlogloss:0.06912
[34]	train-mlogloss:0.12926	eval-mlogloss:0.06884
[35]	train-mlogloss:0.12927	eval-mlogloss:0.06891
[36]	train-mlogloss:0.12930	eval-mlogloss:0.06880
[37]	train-mlogloss:0.12930	eval-mlogloss:0.06877
[38]	train-mlogloss:0.12793	eval-mlogloss:0.06637
[39]	train-mlogloss:0.12717	eval-mlogloss:0.06636
[40]	train-mlogloss:0.12608	eval-mlogloss:0.06708
[41]	train-mlogloss:0.12609	eval-mlogloss:0.06704
[42]	train-mlogloss:0.12619	eval-mlogloss:0.06713
[43]	train-mlogloss:0.12622	eval-mlogloss:0.06717
[44]	train-mlogloss:0.12588	eval-mlogloss:0.06692
[45]	train-mlogloss:0.12599	eval-mlogloss:0.06705
[46]	train-mlogloss:0.12586	eval-mlogloss:0.06684
[47]	train-mlogloss:0.12584	eval-mlogloss:0.06689
[48]	train-mlogloss:0.12587	eval-mlogloss:0.06676
[49]	train-mlogloss:0.12580	eval-mlogloss:0.06679
[50]	train-mlogloss:0.12508	eval-mlogloss:0.06558
[51]	train-mlogloss:0.12503	eval-mlogloss:0.06563
[52]	train-mlogloss:0.12506	eval-mlogloss:0.06580
[53]	train-mlogloss:0.12504	eval-mlogloss:0.06578
[54]	train-mlogloss:0.12504	eval-mlogloss:0.06566
[55]	train-mlogloss:0.12502	eval-mlogloss:0.06568
[56]	train-mlogloss:0.12502	eval-mlogloss:0.06565
[57]	train-mlogloss:0.12492	eval-mlogloss:0.06422
[58]	train-mlogloss:0.12490	eval-mlogloss:0.06430
[59]	train-mlogloss:0.12447	eval-mlogloss:0.06412
[60]	train-mlogloss:0.12449	eval-mlogloss:0.06417
[61]	train-mlogloss:0.12445	eval-mlogloss:0.06423
[62]	train-mlogloss:0.12443	eval-mlogloss:0.06433
[63]	train-mlogloss:0.12443	eval-mlogloss:0.06438
[64]	train-mlogloss:0.12443	eval-mlogloss:0.06443
[65]	train-mlogloss:0.12446	eval-mlogloss:0.06448
[66]	train-mlogloss:0.12443	eval-mlogloss:0.06432
[67]	train-mlogloss:0.12445	eval-mlogloss:0.06450
[68]	train-mlogloss:0.12365	eval-mlogloss:0.06513
[69]	train-mlogloss:0.12365	eval-mlogloss:0.06500
[70]	train-mlogloss:0.12364	eval-mlogloss:0.06501
[71]	train-mlogloss:0.12367	eval-mlogloss:0.06526
[72]	train-mlogloss:0.12374	eval-mlogloss:0.06539
[73]	train-mlogloss:0.12366	eval-mlogloss:0.06513
[74]	train-mlogloss:0.12361	eval-mlogloss:0.06522
[75]	train-mlogloss:0.12368	eval-mlogloss:0.06517
[76]	train-mlogloss:0.12371	eval-mlogloss:0.06516
[77]	train-mlogloss:0.12362	eval-mlogloss:0.06460
[78]	train-mlogloss:0.12364	eval-mlogloss:0.06453
[79]	train-mlogloss:0.12348	eval-mlogloss:0.06455
[80]	train-mlogloss:0.12283	eval-mlogloss:0.06446
[81]	train-mlogloss:0.12284	eval-mlogloss:0.06444
[82]	train-mlogloss:0.12288	eval-mlogloss:0.06457
[83]	train-mlogloss:0.12284	eval-mlogloss:0.06447
[84]	train-mlogloss:0.12284	eval-mlogloss:0.06448
[85]	train-mlogloss:0.12286	eval-mlogloss:0.06451
[86]	train-mlogloss:0.12287	eval-mlogloss:0.06447
[87]	train-mlogloss:0.12286	eval-mlogloss:0.06455
[88]	train-mlogloss:0.12281	eval-mlogloss:0.06446
[89]	train-mlogloss:0.12281	eval-mlogloss:0.06441

c:\Users\LOQ\anaconda3\Lib\site-packages\optuna\integration\xgboost.py:14: FutureWarning:

`optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.

[I 2026-08-19 16:57:34,089] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.00026044898401805317, 'alpha': 2.0029303880783146e-06, 'eta': 0.22585484883249554, 'gamma': 0.22457657025748454, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8081496973474069, 'colsample_bytree': 0.7378646224969284}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.02428	eval-mlogloss:1.02794
[1]	train-mlogloss:0.94349	eval-mlogloss:0.94230
[2]	train-mlogloss:0.91426	eval-mlogloss:0.91832
[3]	train-mlogloss:0.88427	eval-mlogloss:0.88704
[4]	train-mlogloss:0.83232	eval-mlogloss:0.83360
[5]	train-mlogloss:0.80528	eval-mlogloss:0.80719
[6]	train-mlogloss:0.76078	eval-mlogloss:0.76076
[7]	train-mlogloss:0.73303	eval-mlogloss:0.73148
[8]	train-mlogloss:0.70097	eval-mlogloss:0.70143
[9]	train-mlogloss:0.67334	eval-mlogloss:0.67306
[10]	train-mlogloss:0.66814	eval-mlogloss:0.66967
[11]	train-mlogloss:0.63402	eval-mlogloss:0.63371
[12]	train-mlogloss:0.61705	eval-mlogloss:0.61574
[13]	train-mlogloss:0.59391	eval-mlogloss:0.58942
[14]	train-mlogloss:0.57892	eval-mlogloss:0.57305
[15]	train-mlogloss:0.56249	eval-mlogloss:0.55505
[16]	train-mlogloss:0.54419	eval-mlogloss:0.53409
[17]	train-mlogloss:0.53566	eval-mlogloss:0.52550
[18]	train-mlogloss:0.52224	eval-mlogloss:0.51043
[19]	train-mlogloss:0.51047	eval-mlogloss:0.49696
[20]	train-mlogloss:0.48931	eval-mlogloss:0.47195
[21]	train-mlogloss:0.48038	eval-mlogloss:0.46277
[22]	train-mlogloss:0.46388	eval-mlogloss:0.44194
[23]	train-mlogloss:0.44694	eval-mlogloss:0.42289
[24]	train-mlogloss:0.43140	eval-mlogloss:0.40512
[25]	train-mlogloss:0.41769	eval-mlogloss:0.38916
[26]	train-mlogloss:0.40153	eval-mlogloss:0.37121
[27]	train-mlogloss:0.38676	eval-mlogloss:0.35487
[28]	train-mlogloss:0.38479	eval-mlogloss:0.35358
[29]	train-mlogloss:0.38487	eval-mlogloss:0.35350
[30]	train-mlogloss:0.37916	eval-mlogloss:0.34680
[31]	train-mlogloss:0.37656	eval-mlogloss:0.34307
[32]	train-mlogloss:0.36948	eval-mlogloss:0.33357
[33]	train-mlogloss:0.36331	eval-mlogloss:0.32605
[34]	train-mlogloss:0.36211	eval-mlogloss:0.32430
[35]	train-mlogloss:0.35557	eval-mlogloss:0.31620
[36]	train-mlogloss:0.35550	eval-mlogloss:0.31621
[37]	train-mlogloss:0.35481	eval-mlogloss:0.31447
[38]	train-mlogloss:0.34656	eval-mlogloss:0.30385
[39]	train-mlogloss:0.34600	eval-mlogloss:0.30353
[40]	train-mlogloss:0.34002	eval-mlogloss:0.29628
[41]	train-mlogloss:0.34002	eval-mlogloss:0.29630
[42]	train-mlogloss:0.33998	eval-mlogloss:0.29640
[43]	train-mlogloss:0.33951	eval-mlogloss:0.29518
[44]	train-mlogloss:0.33951	eval-mlogloss:0.29519
[45]	train-mlogloss:0.33561	eval-mlogloss:0.29057
[46]	train-mlogloss:0.33558	eval-mlogloss:0.29061
[47]	train-mlogloss:0.33166	eval-mlogloss:0.28597
[48]	train-mlogloss:0.33170	eval-mlogloss:0.28596
[49]	train-mlogloss:0.33173	eval-mlogloss:0.28601
[50]	train-mlogloss:0.33126	eval-mlogloss:0.28564
[51]	train-mlogloss:0.33088	eval-mlogloss:0.28522
[52]	train-mlogloss:0.32639	eval-mlogloss:0.27889
[53]	train-mlogloss:0.32148	eval-mlogloss:0.27296
[54]	train-mlogloss:0.32151	eval-mlogloss:0.27286
[55]	train-mlogloss:0.32152	eval-mlogloss:0.27283
[56]	train-mlogloss:0.32155	eval-mlogloss:0.27289
[57]	train-mlogloss:0.32119	eval-mlogloss:0.27286
[58]	train-mlogloss:0.32064	eval-mlogloss:0.27259
[59]	train-mlogloss:0.32064	eval-mlogloss:0.27255
[60]	train-mlogloss:0.32067	eval-mlogloss:0.27271
[61]	train-mlogloss:0.32015	eval-mlogloss:0.27217
[62]	train-mlogloss:0.31984	eval-mlogloss:0.27196
[63]	train-mlogloss:0.31942	eval-mlogloss:0.27089
[64]	train-mlogloss:0.31938	eval-mlogloss:0.27070
[65]	train-mlogloss:0.31938	eval-mlogloss:0.27066
[66]	train-mlogloss:0.31938	eval-mlogloss:0.27064
[67]	train-mlogloss:0.31889	eval-mlogloss:0.27040
[68]	train-mlogloss:0.31890	eval-mlogloss:0.27048
[69]	train-mlogloss:0.31892	eval-mlogloss:0.27059
[70]	train-mlogloss:0.31855	eval-mlogloss:0.27012
[71]	train-mlogloss:0.31807	eval-mlogloss:0.26963
[72]	train-mlogloss:0.31695	eval-mlogloss:0.26843
[73]	train-mlogloss:0.31694	eval-mlogloss:0.26824
[74]	train-mlogloss:0.31693	eval-mlogloss:0.26841
[75]	train-mlogloss:0.31689	eval-mlogloss:0.26814
[76]	train-mlogloss:0.31688	eval-mlogloss:0.26802
[77]	train-mlogloss:0.31685	eval-mlogloss:0.26756
[78]	train-mlogloss:0.31685	eval-mlogloss:0.26741
[79]	train-mlogloss:0.31684	eval-mlogloss:0.26751
[80]	train-mlogloss:0.31642	eval-mlogloss:0.26731
[81]	train-mlogloss:0.31643	eval-mlogloss:0.26731
[82]	train-mlogloss:0.31599	eval-mlogloss:0.26701
[83]	train-mlogloss:0.31561	eval-mlogloss:0.26577
[84]	train-mlogloss:0.31556	eval-mlogloss:0.26584
[85]	train-mlogloss:0.31556	eval-mlogloss:0.26595
[86]	train-mlogloss:0.31555	eval-mlogloss:0.26592
[87]	train-mlogloss:0.31555	eval-mlogloss:0.26624
[88]	train-mlogloss:0.31553	eval-mlogloss:0.26605
[89]	train-mlogloss:0.31552	eval-mlogloss:0.26618
[90]	train-mlogloss:0.31552	eval-mlogloss:0.26616
[91]	train-mlogloss:0.31553	eval-mlogloss:0.26589
[92]	train-mlogloss:0.31502	eval-mlogloss:0.26411
[93]	train-mlogloss:0.31483	eval-mlogloss:0.26369
[94]	train-mlogloss:0.31483	eval-mlogloss:0.26397
[95]	train-mlogloss:0.31481	eval-mlogloss:0.26409
[96]	train-mlogloss:0.31479	eval-mlogloss:0.26410
[97]	train-mlogloss:0.31477	eval-mlogloss:0.26428
[98]	train-mlogloss:0.31439	eval-mlogloss:0.26405
[99]	train-mlogloss:0.31439	eval-mlogloss:0.26376
[100]	train-mlogloss:0.31440	eval-mlogloss:0.26380
[101]	train-mlogloss:0.31441	eval-mlogloss:0.26369
[102]	train-mlogloss:0.31438	eval-mlogloss:0.26381
[103]	train-mlogloss:0.31436	eval-mlogloss:0.26402
[104]	train-mlogloss:0.31388	eval-mlogloss:0.26375
[105]	train-mlogloss:0.31389	eval-mlogloss:0.26357
[106]	train-mlogloss:0.31389	eval-mlogloss:0.26350
[107]	train-mlogloss:0.31040	eval-mlogloss:0.25925
[108]	train-mlogloss:0.31039	eval-mlogloss:0.25926
[109]	train-mlogloss:0.31038	eval-mlogloss:0.25951
[110]	train-mlogloss:0.31037	eval-mlogloss:0.25954
[111]	train-mlogloss:0.31037	eval-mlogloss:0.25978
[112]	train-mlogloss:0.31037	eval-mlogloss:0.25980
[113]	train-mlogloss:0.31037	eval-mlogloss:0.25969
[114]	train-mlogloss:0.31037	eval-mlogloss:0.25970
[115]	train-mlogloss:0.31037	eval-mlogloss:0.25971
[116]	train-mlogloss:0.31037	eval-mlogloss:0.25985
[117]	train-mlogloss:0.30655	eval-mlogloss:0.25560
[118]	train-mlogloss:0.30656	eval-mlogloss:0.25569
[119]	train-mlogloss:0.30596	eval-mlogloss:0.25557
[120]	train-mlogloss:0.30558	eval-mlogloss:0.25531
[121]	train-mlogloss:0.30563	eval-mlogloss:0.25558
[122]	train-mlogloss:0.30559	eval-mlogloss:0.25547
[123]	train-mlogloss:0.30555	eval-mlogloss:0.25507
[124]	train-mlogloss:0.30553	eval-mlogloss:0.25494
[125]	train-mlogloss:0.30549	eval-mlogloss:0.25464
[126]	train-mlogloss:0.30547	eval-mlogloss:0.25440
[127]	train-mlogloss:0.30549	eval-mlogloss:0.25455
[128]	train-mlogloss:0.30547	eval-mlogloss:0.25447
[129]	train-mlogloss:0.30546	eval-mlogloss:0.25439
[130]	train-mlogloss:0.30276	eval-mlogloss:0.25012
[131]	train-mlogloss:0.30233	eval-mlogloss:0.24870
[132]	train-mlogloss:0.30234	eval-mlogloss:0.24859
[133]	train-mlogloss:0.30235	eval-mlogloss:0.24859
[134]	train-mlogloss:0.30235	eval-mlogloss:0.24854
[135]	train-mlogloss:0.30205	eval-mlogloss:0.24739
[136]	train-mlogloss:0.30202	eval-mlogloss:0.24765
[137]	train-mlogloss:0.30202	eval-mlogloss:0.24760
[138]	train-mlogloss:0.30206	eval-mlogloss:0.24730
[139]	train-mlogloss:0.30190	eval-mlogloss:0.24720
[140]	train-mlogloss:0.30195	eval-mlogloss:0.24691
[141]	train-mlogloss:0.30197	eval-mlogloss:0.24680
[142]	train-mlogloss:0.30162	eval-mlogloss:0.24666
[143]	train-mlogloss:0.30161	eval-mlogloss:0.24675
[144]	train-mlogloss:0.30161	eval-mlogloss:0.24674
[145]	train-mlogloss:0.30118	eval-mlogloss:0.24675
[146]	train-mlogloss:0.30117	eval-mlogloss:0.24697
[147]	train-mlogloss:0.30117	eval-mlogloss:0.24692
[148]	train-mlogloss:0.30117	eval-mlogloss:0.24715
[149]	train-mlogloss:0.30117	eval-mlogloss:0.24704
[150]	train-mlogloss:0.30118	eval-mlogloss:0.24730
[151]	train-mlogloss:0.30118	eval-mlogloss:0.24722
[152]	train-mlogloss:0.30118	eval-mlogloss:0.24732
[153]	train-mlogloss:0.30117	eval-mlogloss:0.24706
[154]	train-mlogloss:0.30082	eval-mlogloss:0.24691
[155]	train-mlogloss:0.30082	eval-mlogloss:0.24685
[156]	train-mlogloss:0.30001	eval-mlogloss:0.24559
[157]	train-mlogloss:0.30004	eval-mlogloss:0.24582
[158]	train-mlogloss:0.30005	eval-mlogloss:0.24604
[159]	train-mlogloss:0.30003	eval-mlogloss:0.24584
[160]	train-mlogloss:0.30002	eval-mlogloss:0.24571
[161]	train-mlogloss:0.30001	eval-mlogloss:0.24549
[162]	train-mlogloss:0.30000	eval-mlogloss:0.24540
[163]	train-mlogloss:0.30000	eval-mlogloss:0.24550
[164]	train-mlogloss:0.30001	eval-mlogloss:0.24558
[165]	train-mlogloss:0.30001	eval-mlogloss:0.24567
[166]	train-mlogloss:0.30000	eval-mlogloss:0.24551
[167]	train-mlogloss:0.30002	eval-mlogloss:0.24571
[168]	train-mlogloss:0.30003	eval-mlogloss:0.24559
[169]	train-mlogloss:0.30001	eval-mlogloss:0.24536
[170]	train-mlogloss:0.30002	eval-mlogloss:0.24552
[171]	train-mlogloss:0.30000	eval-mlogloss:0.24548
[172]	train-mlogloss:0.30000	eval-mlogloss:0.24532
[173]	train-mlogloss:0.30000	eval-mlogloss:0.24536
[174]	train-mlogloss:0.30000	eval-mlogloss:0.24543
[175]	train-mlogloss:0.29969	eval-mlogloss:0.24426
[176]	train-mlogloss:0.29944	eval-mlogloss:0.24420
[177]	train-mlogloss:0.29945	eval-mlogloss:0.24408
[178]	train-mlogloss:0.29943	eval-mlogloss:0.24389
[179]	train-mlogloss:0.29943	eval-mlogloss:0.24384
[180]	train-mlogloss:0.29942	eval-mlogloss:0.24372
[181]	train-mlogloss:0.29945	eval-mlogloss:0.24337
[182]	train-mlogloss:0.29951	eval-mlogloss:0.24307
[183]	train-mlogloss:0.29949	eval-mlogloss:0.24312
[184]	train-mlogloss:0.29947	eval-mlogloss:0.24326
[185]	train-mlogloss:0.29952	eval-mlogloss:0.24303
[186]	train-mlogloss:0.29947	eval-mlogloss:0.24328
[187]	train-mlogloss:0.29944	eval-mlogloss:0.24349
[188]	train-mlogloss:0.29928	eval-mlogloss:0.24377
[189]	train-mlogloss:0.29895	eval-mlogloss:0.24242
[190]	train-mlogloss:0.29898	eval-mlogloss:0.24228
[191]	train-mlogloss:0.29900	eval-mlogloss:0.24220
[192]	train-mlogloss:0.29901	eval-mlogloss:0.24218
[193]	train-mlogloss:0.29899	eval-mlogloss:0.24224
[194]	train-mlogloss:0.29896	eval-mlogloss:0.24237
[195]	train-mlogloss:0.29894	eval-mlogloss:0.24247
[196]	train-mlogloss:0.29895	eval-mlogloss:0.24243
[197]	train-mlogloss:0.29894	eval-mlogloss:0.24248
[198]	train-mlogloss:0.29897	eval-mlogloss:0.24233
[199]	train-mlogloss:0.29681	eval-mlogloss:0.23989
[200]	train-mlogloss:0.29681	eval-mlogloss:0.23990
[201]	train-mlogloss:0.29681	eval-mlogloss:0.23984
[202]	train-mlogloss:0.29682	eval-mlogloss:0.23994
[203]	train-mlogloss:0.29684	eval-mlogloss:0.23996
[204]	train-mlogloss:0.29654	eval-mlogloss:0.23957
[205]	train-mlogloss:0.29333	eval-mlogloss:0.23586
[206]	train-mlogloss:0.29338	eval-mlogloss:0.23584
[207]	train-mlogloss:0.29334	eval-mlogloss:0.23567
[208]	train-mlogloss:0.29337	eval-mlogloss:0.23591
[209]	train-mlogloss:0.29336	eval-mlogloss:0.23583
[210]	train-mlogloss:0.29344	eval-mlogloss:0.23603
[211]	train-mlogloss:0.29339	eval-mlogloss:0.23611
[212]	train-mlogloss:0.29311	eval-mlogloss:0.23603
[213]	train-mlogloss:0.29309	eval-mlogloss:0.23624
[214]	train-mlogloss:0.29311	eval-mlogloss:0.23636
[215]	train-mlogloss:0.29308	eval-mlogloss:0.23615
[216]	train-mlogloss:0.29308	eval-mlogloss:0.23637
[217]	train-mlogloss:0.29301	eval-mlogloss:0.23607
[218]	train-mlogloss:0.29299	eval-mlogloss:0.23611
[219]	train-mlogloss:0.29295	eval-mlogloss:0.23593
[220]	train-mlogloss:0.29295	eval-mlogloss:0.23582
[221]	train-mlogloss:0.29295	eval-mlogloss:0.23597
[222]	train-mlogloss:0.29293	eval-mlogloss:0.23605
[223]	train-mlogloss:0.28959	eval-mlogloss:0.23205
[224]	train-mlogloss:0.28921	eval-mlogloss:0.23189
[225]	train-mlogloss:0.28919	eval-mlogloss:0.23183
[226]	train-mlogloss:0.28921	eval-mlogloss:0.23179
[227]	train-mlogloss:0.28917	eval-mlogloss:0.23169
[228]	train-mlogloss:0.28914	eval-mlogloss:0.23148
[229]	train-mlogloss:0.28916	eval-mlogloss:0.23142
[230]	train-mlogloss:0.28915	eval-mlogloss:0.23117
[231]	train-mlogloss:0.28891	eval-mlogloss:0.23096
[232]	train-mlogloss:0.28891	eval-mlogloss:0.23115
[233]	train-mlogloss:0.28889	eval-mlogloss:0.23105
[234]	train-mlogloss:0.28892	eval-mlogloss:0.23111
[235]	train-mlogloss:0.28890	eval-mlogloss:0.23106
[236]	train-mlogloss:0.28888	eval-mlogloss:0.23094
[237]	train-mlogloss:0.28888	eval-mlogloss:0.23100
[238]	train-mlogloss:0.28889	eval-mlogloss:0.23075
[239]	train-mlogloss:0.28894	eval-mlogloss:0.23055
[240]	train-mlogloss:0.28896	eval-mlogloss:0.23045
[241]	train-mlogloss:0.28898	eval-mlogloss:0.23038
[242]	train-mlogloss:0.28898	eval-mlogloss:0.23036
[243]	train-mlogloss:0.28898	eval-mlogloss:0.23034
[244]	train-mlogloss:0.28894	eval-mlogloss:0.23047
[245]	train-mlogloss:0.28891	eval-mlogloss:0.23063
[246]	train-mlogloss:0.28889	eval-mlogloss:0.23088
[247]	train-mlogloss:0.28887	eval-mlogloss:0.23092
[248]	train-mlogloss:0.28865	eval-mlogloss:0.22979
[249]	train-mlogloss:0.28867	eval-mlogloss:0.22968
[250]	train-mlogloss:0.28867	eval-mlogloss:0.22970
[251]	train-mlogloss:0.28865	eval-mlogloss:0.22978
[252]	train-mlogloss:0.28868	eval-mlogloss:0.22963
[253]	train-mlogloss:0.28873	eval-mlogloss:0.22945
[254]	train-mlogloss:0.28873	eval-mlogloss:0.22951
[255]	train-mlogloss:0.28877	eval-mlogloss:0.22936
[256]	train-mlogloss:0.28875	eval-mlogloss:0.22945
[257]	train-mlogloss:0.28875	eval-mlogloss:0.22946
[258]	train-mlogloss:0.28871	eval-mlogloss:0.22959
[259]	train-mlogloss:0.28871	eval-mlogloss:0.22962
[260]	train-mlogloss:0.28871	eval-mlogloss:0.22977
[261]	train-mlogloss:0.28870	eval-mlogloss:0.22974
[262]	train-mlogloss:0.28868	eval-mlogloss:0.22989
[263]	train-mlogloss:0.28858	eval-mlogloss:0.23001
[264]	train-mlogloss:0.28857	eval-mlogloss:0.23012
[265]	train-mlogloss:0.28854	eval-mlogloss:0.23031
[266]	train-mlogloss:0.28855	eval-mlogloss:0.23030
[267]	train-mlogloss:0.28854	eval-mlogloss:0.23035
[268]	train-mlogloss:0.28854	eval-mlogloss:0.23019
[269]	train-mlogloss:0.28855	eval-mlogloss:0.23032
[270]	train-mlogloss:0.28856	eval-mlogloss:0.23019
[271]	train-mlogloss:0.28852	eval-mlogloss:0.23044
[272]	train-mlogloss:0.28851	eval-mlogloss:0.23041
[273]	train-mlogloss:0.28850	eval-mlogloss:0.23043
[274]	train-mlogloss:0.28850	eval-mlogloss:0.23036
[275]	train-mlogloss:0.28850	eval-mlogloss:0.23034
[276]	train-mlogloss:0.28851	eval-mlogloss:0.23028
[277]	train-mlogloss:0.28851	eval-mlogloss:0.23022
[278]	train-mlogloss:0.28854	eval-mlogloss:0.23009
[279]	train-mlogloss:0.28854	eval-mlogloss:0.23011
[280]	train-mlogloss:0.28851	eval-mlogloss:0.23028
[281]	train-mlogloss:0.28850	eval-mlogloss:0.23038
[282]	train-mlogloss:0.28855	eval-mlogloss:0.23020
[283]	train-mlogloss:0.28853	eval-mlogloss:0.23029
[284]	train-mlogloss:0.28852	eval-mlogloss:0.23030
[285]	train-mlogloss:0.28850	eval-mlogloss:0.23038

[I 2026-08-19 16:57:34,641] Trial 1 finished with value: 1.0 and parameters: {'lambda': 3.4993664438965766e-06, 'alpha': 1.047111469771371e-06, 'eta': 0.07371986462813385, 'gamma': 0.4369276370349716, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.5896881361720264, 'colsample_bytree': 0.40371561781864607}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.79371	eval-mlogloss:0.77694

[I 2026-08-19 16:57:34,665] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85849	eval-mlogloss:0.85764

[I 2026-08-19 16:57:34,679] Trial 3 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.82008	eval-mlogloss:0.80425

[I 2026-08-19 16:57:34,689] Trial 4 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.90597	eval-mlogloss:0.88552

[I 2026-08-19 16:57:34,701] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96685	eval-mlogloss:0.96631

[I 2026-08-19 16:57:34,709] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84696	eval-mlogloss:0.83457

[I 2026-08-19 16:57:34,718] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84277	eval-mlogloss:0.83542

[I 2026-08-19 16:57:34,725] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.81767	eval-mlogloss:0.82234

[I 2026-08-19 16:57:34,732] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03536	eval-mlogloss:1.03368
[1]	train-mlogloss:0.97481	eval-mlogloss:0.97369
[2]	train-mlogloss:0.92019	eval-mlogloss:0.91677
[3]	train-mlogloss:0.87064	eval-mlogloss:0.86661

[I 2026-08-19 16:57:34,760] Trial 10 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07185	eval-mlogloss:1.07228
[1]	train-mlogloss:1.04619	eval-mlogloss:1.04615
[2]	train-mlogloss:1.02085	eval-mlogloss:1.01884
[3]	train-mlogloss:0.99739	eval-mlogloss:0.99407
[4]	train-mlogloss:0.97365	eval-mlogloss:0.96925
[5]	train-mlogloss:0.95122	eval-mlogloss:0.94540
[6]	train-mlogloss:0.93091	eval-mlogloss:0.92342
[7]	train-mlogloss:0.91753	eval-mlogloss:0.91014
[8]	train-mlogloss:0.89646	eval-mlogloss:0.88833
[9]	train-mlogloss:0.87632	eval-mlogloss:0.86688
[10]	train-mlogloss:0.86180	eval-mlogloss:0.85283
[11]	train-mlogloss:0.84289	eval-mlogloss:0.83260
[12]	train-mlogloss:0.82861	eval-mlogloss:0.81762
[13]	train-mlogloss:0.81620	eval-mlogloss:0.80463
[14]	train-mlogloss:0.80199	eval-mlogloss:0.78935
[15]	train-mlogloss:0.78490	eval-mlogloss:0.77083
[16]	train-mlogloss:0.77180	eval-mlogloss:0.75776
[17]	train-mlogloss:0.75566	eval-mlogloss:0.74066
[18]	train-mlogloss:0.74346	eval-mlogloss:0.72867
[19]	train-mlogloss:0.72825	eval-mlogloss:0.71204
[20]	train-mlogloss:0.71661	eval-mlogloss:0.69972
[21]	train-mlogloss:0.70213	eval-mlogloss:0.68432
[22]	train-mlogloss:0.68807	eval-mlogloss:0.66914
[23]	train-mlogloss:0.67449	eval-mlogloss:0.65489
[24]	train-mlogloss:0.66156	eval-mlogloss:0.64127
[25]	train-mlogloss:0.64816	eval-mlogloss:0.62706
[26]	train-mlogloss:0.63531	eval-mlogloss:0.61290
[27]	train-mlogloss:0.62262	eval-mlogloss:0.59971
[28]	train-mlogloss:0.61101	eval-mlogloss:0.58668
[29]	train-mlogloss:0.59993	eval-mlogloss:0.57480
[30]	train-mlogloss:0.59001	eval-mlogloss:0.56361
[31]	train-mlogloss:0.57893	eval-mlogloss:0.55181
[32]	train-mlogloss:0.56796	eval-mlogloss:0.54041
[33]	train-mlogloss:0.55713	eval-mlogloss:0.52885
[34]	train-mlogloss:0.54713	eval-mlogloss:0.51795
[35]	train-mlogloss:0.53819	eval-mlogloss:0.50793
[36]	train-mlogloss:0.53105	eval-mlogloss:0.50008
[37]	train-mlogloss:0.52361	eval-mlogloss:0.49210
[38]	train-mlogloss:0.51512	eval-mlogloss:0.48307
[39]	train-mlogloss:0.50831	eval-mlogloss:0.47546
[40]	train-mlogloss:0.50040	eval-mlogloss:0.46664
[41]	train-mlogloss:0.49264	eval-mlogloss:0.45797
[42]	train-mlogloss:0.48421	eval-mlogloss:0.44839
[43]	train-mlogloss:0.47912	eval-mlogloss:0.44223
[44]	train-mlogloss:0.47277	eval-mlogloss:0.43548
[45]	train-mlogloss:0.46773	eval-mlogloss:0.42984
[46]	train-mlogloss:0.46174	eval-mlogloss:0.42308
[47]	train-mlogloss:0.45455	eval-mlogloss:0.41561
[48]	train-mlogloss:0.44803	eval-mlogloss:0.40861
[49]	train-mlogloss:0.44088	eval-mlogloss:0.40088
[50]	train-mlogloss:0.43669	eval-mlogloss:0.39646
[51]	train-mlogloss:0.43225	eval-mlogloss:0.39147
[52]	train-mlogloss:0.42558	eval-mlogloss:0.38405
[53]	train-mlogloss:0.42012	eval-mlogloss:0.37796
[54]	train-mlogloss:0.41462	eval-mlogloss:0.37241
[55]	train-mlogloss:0.40943	eval-mlogloss:0.36711
[56]	train-mlogloss:0.40579	eval-mlogloss:0.36310
[57]	train-mlogloss:0.40116	eval-mlogloss:0.35823
[58]	train-mlogloss:0.39680	eval-mlogloss:0.35341
[59]	train-mlogloss:0.39259	eval-mlogloss:0.34901
[60]	train-mlogloss:0.38826	eval-mlogloss:0.34418
[61]	train-mlogloss:0.38434	eval-mlogloss:0.34013
[62]	train-mlogloss:0.38057	eval-mlogloss:0.33549
[63]	train-mlogloss:0.37637	eval-mlogloss:0.33106
[64]	train-mlogloss:0.37222	eval-mlogloss:0.32651
[65]	train-mlogloss:0.36916	eval-mlogloss:0.32308
[66]	train-mlogloss:0.36552	eval-mlogloss:0.31928
[67]	train-mlogloss:0.36268	eval-mlogloss:0.31631
[68]	train-mlogloss:0.35993	eval-mlogloss:0.31337
[69]	train-mlogloss:0.35726	eval-mlogloss:0.31036
[70]	train-mlogloss:0.35419	eval-mlogloss:0.30699
[71]	train-mlogloss:0.35149	eval-mlogloss:0.30384
[72]	train-mlogloss:0.34764	eval-mlogloss:0.29952
[73]	train-mlogloss:0.34517	eval-mlogloss:0.29679
[74]	train-mlogloss:0.34153	eval-mlogloss:0.29272
[75]	train-mlogloss:0.33858	eval-mlogloss:0.28929
[76]	train-mlogloss:0.33509	eval-mlogloss:0.28560
[77]	train-mlogloss:0.33239	eval-mlogloss:0.28257
[78]	train-mlogloss:0.32997	eval-mlogloss:0.27978
[79]	train-mlogloss:0.32763	eval-mlogloss:0.27717
[80]	train-mlogloss:0.32652	eval-mlogloss:0.27598
[81]	train-mlogloss:0.32526	eval-mlogloss:0.27436
[82]	train-mlogloss:0.32241	eval-mlogloss:0.27124
[83]	train-mlogloss:0.31976	eval-mlogloss:0.26845
[84]	train-mlogloss:0.31840	eval-mlogloss:0.26697
[85]	train-mlogloss:0.31790	eval-mlogloss:0.26649
[86]	train-mlogloss:0.31517	eval-mlogloss:0.26315
[87]	train-mlogloss:0.31298	eval-mlogloss:0.26066
[88]	train-mlogloss:0.31182	eval-mlogloss:0.25948
[89]	train-mlogloss:0.31042	eval-mlogloss:0.25774
[90]	train-mlogloss:0.30934	eval-mlogloss:0.25640
[91]	train-mlogloss:0.30881	eval-mlogloss:0.25546
[92]	train-mlogloss:0.30692	eval-mlogloss:0.25304
[93]	train-mlogloss:0.30502	eval-mlogloss:0.25095
[94]	train-mlogloss:0.30491	eval-mlogloss:0.25089
[95]	train-mlogloss:0.30421	eval-mlogloss:0.24998
[96]	train-mlogloss:0.30287	eval-mlogloss:0.24830
[97]	train-mlogloss:0.30157	eval-mlogloss:0.24665
[98]	train-mlogloss:0.30055	eval-mlogloss:0.24552
[99]	train-mlogloss:0.30046	eval-mlogloss:0.24538
[100]	train-mlogloss:0.29984	eval-mlogloss:0.24460
[101]	train-mlogloss:0.29729	eval-mlogloss:0.24195
[102]	train-mlogloss:0.29609	eval-mlogloss:0.24036
[103]	train-mlogloss:0.29589	eval-mlogloss:0.24030
[104]	train-mlogloss:0.29490	eval-mlogloss:0.23927
[105]	train-mlogloss:0.29225	eval-mlogloss:0.23604
[106]	train-mlogloss:0.29094	eval-mlogloss:0.23458
[107]	train-mlogloss:0.28968	eval-mlogloss:0.23302
[108]	train-mlogloss:0.28962	eval-mlogloss:0.23295
[109]	train-mlogloss:0.28929	eval-mlogloss:0.23255
[110]	train-mlogloss:0.28901	eval-mlogloss:0.23201
[111]	train-mlogloss:0.28892	eval-mlogloss:0.23178
[112]	train-mlogloss:0.28636	eval-mlogloss:0.22895
[113]	train-mlogloss:0.28420	eval-mlogloss:0.22644
[114]	train-mlogloss:0.28384	eval-mlogloss:0.22601
[115]	train-mlogloss:0.28181	eval-mlogloss:0.22381
[116]	train-mlogloss:0.28085	eval-mlogloss:0.22263
[117]	train-mlogloss:0.27990	eval-mlogloss:0.22135
[118]	train-mlogloss:0.27770	eval-mlogloss:0.21893
[119]	train-mlogloss:0.27669	eval-mlogloss:0.21781
[120]	train-mlogloss:0.27655	eval-mlogloss:0.21763
[121]	train-mlogloss:0.27637	eval-mlogloss:0.21730
[122]	train-mlogloss:0.27615	eval-mlogloss:0.21708
[123]	train-mlogloss:0.27607	eval-mlogloss:0.21700
[124]	train-mlogloss:0.27606	eval-mlogloss:0.21697
[125]	train-mlogloss:0.27596	eval-mlogloss:0.21664
[126]	train-mlogloss:0.27587	eval-mlogloss:0.21658
[127]	train-mlogloss:0.27584	eval-mlogloss:0.21657
[128]	train-mlogloss:0.27579	eval-mlogloss:0.21649
[129]	train-mlogloss:0.27569	eval-mlogloss:0.21620
[130]	train-mlogloss:0.27488	eval-mlogloss:0.21496
[131]	train-mlogloss:0.27396	eval-mlogloss:0.21357
[132]	train-mlogloss:0.27386	eval-mlogloss:0.21338
[133]	train-mlogloss:0.27380	eval-mlogloss:0.21335
[134]	train-mlogloss:0.27376	eval-mlogloss:0.21324
[135]	train-mlogloss:0.27369	eval-mlogloss:0.21302
[136]	train-mlogloss:0.27362	eval-mlogloss:0.21302
[137]	train-mlogloss:0.27362	eval-mlogloss:0.21301
[138]	train-mlogloss:0.27285	eval-mlogloss:0.21201
[139]	train-mlogloss:0.27270	eval-mlogloss:0.21197
[140]	train-mlogloss:0.27182	eval-mlogloss:0.21079
[141]	train-mlogloss:0.27115	eval-mlogloss:0.20997
[142]	train-mlogloss:0.27115	eval-mlogloss:0.20998
[143]	train-mlogloss:0.27099	eval-mlogloss:0.20980
[144]	train-mlogloss:0.27075	eval-mlogloss:0.20936
[145]	train-mlogloss:0.27062	eval-mlogloss:0.20917
[146]	train-mlogloss:0.26977	eval-mlogloss:0.20809
[147]	train-mlogloss:0.26948	eval-mlogloss:0.20746
[148]	train-mlogloss:0.26947	eval-mlogloss:0.20738
[149]	train-mlogloss:0.26924	eval-mlogloss:0.20693
[150]	train-mlogloss:0.26915	eval-mlogloss:0.20685
[151]	train-mlogloss:0.26885	eval-mlogloss:0.20647
[152]	train-mlogloss:0.26878	eval-mlogloss:0.20641
[153]	train-mlogloss:0.26856	eval-mlogloss:0.20587
[154]	train-mlogloss:0.26841	eval-mlogloss:0.20570
[155]	train-mlogloss:0.26831	eval-mlogloss:0.20563
[156]	train-mlogloss:0.26736	eval-mlogloss:0.20445
[157]	train-mlogloss:0.26734	eval-mlogloss:0.20438
[158]	train-mlogloss:0.26734	eval-mlogloss:0.20443
[159]	train-mlogloss:0.26724	eval-mlogloss:0.20410
[160]	train-mlogloss:0.26717	eval-mlogloss:0.20385
[161]	train-mlogloss:0.26714	eval-mlogloss:0.20390
[162]	train-mlogloss:0.26707	eval-mlogloss:0.20366
[163]	train-mlogloss:0.26704	eval-mlogloss:0.20362
[164]	train-mlogloss:0.26705	eval-mlogloss:0.20363
[165]	train-mlogloss:0.26698	eval-mlogloss:0.20339
[166]	train-mlogloss:0.26674	eval-mlogloss:0.20312
[167]	train-mlogloss:0.26660	eval-mlogloss:0.20309
[168]	train-mlogloss:0.26651	eval-mlogloss:0.20305
[169]	train-mlogloss:0.26640	eval-mlogloss:0.20266
[170]	train-mlogloss:0.26636	eval-mlogloss:0.20262
[171]	train-mlogloss:0.26546	eval-mlogloss:0.20139
[172]	train-mlogloss:0.26540	eval-mlogloss:0.20116
[173]	train-mlogloss:0.26535	eval-mlogloss:0.20112
[174]	train-mlogloss:0.26523	eval-mlogloss:0.20106
[175]	train-mlogloss:0.26515	eval-mlogloss:0.20075
[176]	train-mlogloss:0.26503	eval-mlogloss:0.20067
[177]	train-mlogloss:0.26501	eval-mlogloss:0.20072
[178]	train-mlogloss:0.26495	eval-mlogloss:0.20069
[179]	train-mlogloss:0.26485	eval-mlogloss:0.20062
[180]	train-mlogloss:0.26481	eval-mlogloss:0.20056
[181]	train-mlogloss:0.26478	eval-mlogloss:0.20050
[182]	train-mlogloss:0.26464	eval-mlogloss:0.20043
[183]	train-mlogloss:0.26456	eval-mlogloss:0.20018
[184]	train-mlogloss:0.26454	eval-mlogloss:0.20012
[185]	train-mlogloss:0.26451	eval-mlogloss:0.20017
[186]	train-mlogloss:0.26441	eval-mlogloss:0.20013
[187]	train-mlogloss:0.26435	eval-mlogloss:0.20007
[188]	train-mlogloss:0.26435	eval-mlogloss:0.20011
[189]	train-mlogloss:0.26425	eval-mlogloss:0.19970
[190]	train-mlogloss:0.26425	eval-mlogloss:0.19972
[191]	train-mlogloss:0.26421	eval-mlogloss:0.19966
[192]	train-mlogloss:0.26417	eval-mlogloss:0.19952
[193]	train-mlogloss:0.26408	eval-mlogloss:0.19948
[194]	train-mlogloss:0.26403	eval-mlogloss:0.19929
[195]	train-mlogloss:0.26396	eval-mlogloss:0.19926
[196]	train-mlogloss:0.26392	eval-mlogloss:0.19922
[197]	train-mlogloss:0.26384	eval-mlogloss:0.19918
[198]	train-mlogloss:0.26382	eval-mlogloss:0.19914
[199]	train-mlogloss:0.26302	eval-mlogloss:0.19833
[200]	train-mlogloss:0.26296	eval-mlogloss:0.19831
[201]	train-mlogloss:0.26295	eval-mlogloss:0.19833
[202]	train-mlogloss:0.26285	eval-mlogloss:0.19832
[203]	train-mlogloss:0.26266	eval-mlogloss:0.19810
[204]	train-mlogloss:0.26256	eval-mlogloss:0.19799
[205]	train-mlogloss:0.26180	eval-mlogloss:0.19702
[206]	train-mlogloss:0.26180	eval-mlogloss:0.19702
[207]	train-mlogloss:0.26179	eval-mlogloss:0.19696
[208]	train-mlogloss:0.26172	eval-mlogloss:0.19695
[209]	train-mlogloss:0.26172	eval-mlogloss:0.19694
[210]	train-mlogloss:0.26166	eval-mlogloss:0.19692
[211]	train-mlogloss:0.26158	eval-mlogloss:0.19688
[212]	train-mlogloss:0.26149	eval-mlogloss:0.19684
[213]	train-mlogloss:0.26091	eval-mlogloss:0.19598
[214]	train-mlogloss:0.26082	eval-mlogloss:0.19596
[215]	train-mlogloss:0.26082	eval-mlogloss:0.19594
[216]	train-mlogloss:0.26082	eval-mlogloss:0.19595
[217]	train-mlogloss:0.26076	eval-mlogloss:0.19586
[218]	train-mlogloss:0.26072	eval-mlogloss:0.19581
[219]	train-mlogloss:0.26066	eval-mlogloss:0.19578
[220]	train-mlogloss:0.26066	eval-mlogloss:0.19577
[221]	train-mlogloss:0.26060	eval-mlogloss:0.19572
[222]	train-mlogloss:0.26057	eval-mlogloss:0.19570
[223]	train-mlogloss:0.25983	eval-mlogloss:0.19469
[224]	train-mlogloss:0.25975	eval-mlogloss:0.19465
[225]	train-mlogloss:0.25969	eval-mlogloss:0.19445
[226]	train-mlogloss:0.25960	eval-mlogloss:0.19440
[227]	train-mlogloss:0.25957	eval-mlogloss:0.19428
[228]	train-mlogloss:0.25952	eval-mlogloss:0.19421
[229]	train-mlogloss:0.25953	eval-mlogloss:0.19421
[230]	train-mlogloss:0.25948	eval-mlogloss:0.19414
[231]	train-mlogloss:0.25944	eval-mlogloss:0.19407
[232]	train-mlogloss:0.25938	eval-mlogloss:0.19406
[233]	train-mlogloss:0.25931	eval-mlogloss:0.19401
[234]	train-mlogloss:0.25927	eval-mlogloss:0.19390
[235]	train-mlogloss:0.25921	eval-mlogloss:0.19388
[236]	train-mlogloss:0.25916	eval-mlogloss:0.19368
[237]	train-mlogloss:0.25910	eval-mlogloss:0.19345
[238]	train-mlogloss:0.25888	eval-mlogloss:0.19289
[239]	train-mlogloss:0.25885	eval-mlogloss:0.19284
[240]	train-mlogloss:0.25884	eval-mlogloss:0.19281
[241]	train-mlogloss:0.25880	eval-mlogloss:0.19261
[242]	train-mlogloss:0.25875	eval-mlogloss:0.19259
[243]	train-mlogloss:0.25807	eval-mlogloss:0.19165
[244]	train-mlogloss:0.25798	eval-mlogloss:0.19160
[245]	train-mlogloss:0.25790	eval-mlogloss:0.19133
[246]	train-mlogloss:0.25790	eval-mlogloss:0.19131
[247]	train-mlogloss:0.25787	eval-mlogloss:0.19138
[248]	train-mlogloss:0.25782	eval-mlogloss:0.19116
[249]	train-mlogloss:0.25780	eval-mlogloss:0.19121
[250]	train-mlogloss:0.25780	eval-mlogloss:0.19121
[251]	train-mlogloss:0.25778	eval-mlogloss:0.19120
[252]	train-mlogloss:0.25766	eval-mlogloss:0.19103
[253]	train-mlogloss:0.25762	eval-mlogloss:0.19097
[254]	train-mlogloss:0.25759	eval-mlogloss:0.19093
[255]	train-mlogloss:0.25755	eval-mlogloss:0.19085

[I 2026-08-19 16:57:35,275] Trial 11 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:0.94455	eval-mlogloss:0.93682

[I 2026-08-19 16:57:35,297] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.98574	eval-mlogloss:0.98025

[I 2026-08-19 16:57:35,322] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.91544	eval-mlogloss:0.90927

[I 2026-08-19 16:57:35,346] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05851	eval-mlogloss:1.05557
[1]	train-mlogloss:1.00884	eval-mlogloss:1.00638
[2]	train-mlogloss:0.99777	eval-mlogloss:0.99608
[3]	train-mlogloss:0.97296	eval-mlogloss:0.97259

[I 2026-08-19 16:57:35,377] Trial 15 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.75521	eval-mlogloss:0.73320

[I 2026-08-19 16:57:35,397] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07289	eval-mlogloss:1.07326
[1]	train-mlogloss:1.04789	eval-mlogloss:1.04757
[2]	train-mlogloss:1.02404	eval-mlogloss:1.02225
[3]	train-mlogloss:1.00158	eval-mlogloss:0.99909
[4]	train-mlogloss:0.97900	eval-mlogloss:0.97611
[5]	train-mlogloss:0.95746	eval-mlogloss:0.95401
[6]	train-mlogloss:0.93660	eval-mlogloss:0.93215
[7]	train-mlogloss:0.91626	eval-mlogloss:0.91082
[8]	train-mlogloss:0.89626	eval-mlogloss:0.89001
[9]	train-mlogloss:0.87865	eval-mlogloss:0.87244
[10]	train-mlogloss:0.86015	eval-mlogloss:0.85353
[11]	train-mlogloss:0.84199	eval-mlogloss:0.83408
[12]	train-mlogloss:0.82435	eval-mlogloss:0.81568
[13]	train-mlogloss:0.80718	eval-mlogloss:0.79764
[14]	train-mlogloss:0.79044	eval-mlogloss:0.78026
[15]	train-mlogloss:0.77444	eval-mlogloss:0.76328

[I 2026-08-19 16:57:35,453] Trial 17 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:0.92067	eval-mlogloss:0.91188

[I 2026-08-19 16:57:35,477] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97652	eval-mlogloss:0.97791

[I 2026-08-19 16:57:35,498] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.86015	eval-mlogloss:0.84610

[I 2026-08-19 16:57:35,521] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07461	eval-mlogloss:1.07494
[1]	train-mlogloss:1.05168	eval-mlogloss:1.05160
[2]	train-mlogloss:1.02907	eval-mlogloss:1.02724
[3]	train-mlogloss:1.00786	eval-mlogloss:1.00490
[4]	train-mlogloss:0.98652	eval-mlogloss:0.98258
[5]	train-mlogloss:0.96605	eval-mlogloss:0.96092
[6]	train-mlogloss:0.94842	eval-mlogloss:0.94206
[7]	train-mlogloss:0.93628	eval-mlogloss:0.92990
[8]	train-mlogloss:0.91711	eval-mlogloss:0.91006
[9]	train-mlogloss:0.89861	eval-mlogloss:0.89042
[10]	train-mlogloss:0.88530	eval-mlogloss:0.87757
[11]	train-mlogloss:0.86798	eval-mlogloss:0.85904
[12]	train-mlogloss:0.85484	eval-mlogloss:0.84526
[13]	train-mlogloss:0.84332	eval-mlogloss:0.83319
[14]	train-mlogloss:0.83014	eval-mlogloss:0.81900
[15]	train-mlogloss:0.81420	eval-mlogloss:0.80174
[16]	train-mlogloss:0.80201	eval-mlogloss:0.78960
[17]	train-mlogloss:0.78690	eval-mlogloss:0.77363
[18]	train-mlogloss:0.77543	eval-mlogloss:0.76236
[19]	train-mlogloss:0.76103	eval-mlogloss:0.74666
[20]	train-mlogloss:0.75005	eval-mlogloss:0.73490
[21]	train-mlogloss:0.73640	eval-mlogloss:0.72040
[22]	train-mlogloss:0.72335	eval-mlogloss:0.70674
[23]	train-mlogloss:0.71040	eval-mlogloss:0.69318
[24]	train-mlogloss:0.69811	eval-mlogloss:0.68025
[25]	train-mlogloss:0.68533	eval-mlogloss:0.66672
[26]	train-mlogloss:0.67300	eval-mlogloss:0.65322
[27]	train-mlogloss:0.66067	eval-mlogloss:0.64035
[28]	train-mlogloss:0.64942	eval-mlogloss:0.62780
[29]	train-mlogloss:0.63863	eval-mlogloss:0.61636
[30]	train-mlogloss:0.62899	eval-mlogloss:0.60517
[31]	train-mlogloss:0.61823	eval-mlogloss:0.59376
[32]	train-mlogloss:0.60758	eval-mlogloss:0.58268
[33]	train-mlogloss:0.59700	eval-mlogloss:0.57140
[34]	train-mlogloss:0.58688	eval-mlogloss:0.56040
[35]	train-mlogloss:0.57808	eval-mlogloss:0.55058
[36]	train-mlogloss:0.57109	eval-mlogloss:0.54289
[37]	train-mlogloss:0.56379	eval-mlogloss:0.53509
[38]	train-mlogloss:0.55542	eval-mlogloss:0.52614
[39]	train-mlogloss:0.54843	eval-mlogloss:0.51801
[40]	train-mlogloss:0.54054	eval-mlogloss:0.50925
[41]	train-mlogloss:0.53251	eval-mlogloss:0.50062
[42]	train-mlogloss:0.52413	eval-mlogloss:0.49111
[43]	train-mlogloss:0.51905	eval-mlogloss:0.48500
[44]	train-mlogloss:0.51274	eval-mlogloss:0.47829
[45]	train-mlogloss:0.50764	eval-mlogloss:0.47261
[46]	train-mlogloss:0.50158	eval-mlogloss:0.46578
[47]	train-mlogloss:0.49444	eval-mlogloss:0.45830
[48]	train-mlogloss:0.48763	eval-mlogloss:0.45091
[49]	train-mlogloss:0.48034	eval-mlogloss:0.44306
[50]	train-mlogloss:0.47483	eval-mlogloss:0.43759
[51]	train-mlogloss:0.46849	eval-mlogloss:0.43039
[52]	train-mlogloss:0.46153	eval-mlogloss:0.42281
[53]	train-mlogloss:0.45594	eval-mlogloss:0.41686
[54]	train-mlogloss:0.45049	eval-mlogloss:0.41114
[55]	train-mlogloss:0.44526	eval-mlogloss:0.40524
[56]	train-mlogloss:0.44155	eval-mlogloss:0.40105
[57]	train-mlogloss:0.43581	eval-mlogloss:0.39494
[58]	train-mlogloss:0.43097	eval-mlogloss:0.38952
[59]	train-mlogloss:0.42668	eval-mlogloss:0.38505
[60]	train-mlogloss:0.42231	eval-mlogloss:0.38019
[61]	train-mlogloss:0.41725	eval-mlogloss:0.37502
[62]	train-mlogloss:0.41331	eval-mlogloss:0.37007
[63]	train-mlogloss:0.40898	eval-mlogloss:0.36548
[64]	train-mlogloss:0.40466	eval-mlogloss:0.36075
[65]	train-mlogloss:0.40154	eval-mlogloss:0.35724
[66]	train-mlogloss:0.39781	eval-mlogloss:0.35335
[67]	train-mlogloss:0.39487	eval-mlogloss:0.35028
[68]	train-mlogloss:0.39192	eval-mlogloss:0.34733
[69]	train-mlogloss:0.38839	eval-mlogloss:0.34336
[70]	train-mlogloss:0.38437	eval-mlogloss:0.33864
[71]	train-mlogloss:0.38148	eval-mlogloss:0.33548
[72]	train-mlogloss:0.37736	eval-mlogloss:0.33080
[73]	train-mlogloss:0.37482	eval-mlogloss:0.32797
[74]	train-mlogloss:0.37110	eval-mlogloss:0.32383
[75]	train-mlogloss:0.36802	eval-mlogloss:0.32026
[76]	train-mlogloss:0.36435	eval-mlogloss:0.31653
[77]	train-mlogloss:0.36155	eval-mlogloss:0.31342
[78]	train-mlogloss:0.35876	eval-mlogloss:0.31004
[79]	train-mlogloss:0.35545	eval-mlogloss:0.30642
[80]	train-mlogloss:0.35390	eval-mlogloss:0.30479
[81]	train-mlogloss:0.35100	eval-mlogloss:0.30155
[82]	train-mlogloss:0.34794	eval-mlogloss:0.29801
[83]	train-mlogloss:0.34522	eval-mlogloss:0.29517
[84]	train-mlogloss:0.34303	eval-mlogloss:0.29292
[85]	train-mlogloss:0.34086	eval-mlogloss:0.29059
[86]	train-mlogloss:0.33808	eval-mlogloss:0.28721
[87]	train-mlogloss:0.33581	eval-mlogloss:0.28465
[88]	train-mlogloss:0.33407	eval-mlogloss:0.28275
[89]	train-mlogloss:0.33137	eval-mlogloss:0.27946
[90]	train-mlogloss:0.32904	eval-mlogloss:0.27671
[91]	train-mlogloss:0.32698	eval-mlogloss:0.27429
[92]	train-mlogloss:0.32478	eval-mlogloss:0.27189
[93]	train-mlogloss:0.32276	eval-mlogloss:0.26973
[94]	train-mlogloss:0.32069	eval-mlogloss:0.26774
[95]	train-mlogloss:0.31998	eval-mlogloss:0.26682
[96]	train-mlogloss:0.31866	eval-mlogloss:0.26518
[97]	train-mlogloss:0.31657	eval-mlogloss:0.26280
[98]	train-mlogloss:0.31409	eval-mlogloss:0.26007
[99]	train-mlogloss:0.31392	eval-mlogloss:0.26000
[100]	train-mlogloss:0.31196	eval-mlogloss:0.25791
[101]	train-mlogloss:0.30932	eval-mlogloss:0.25505
[102]	train-mlogloss:0.30811	eval-mlogloss:0.25369
[103]	train-mlogloss:0.30777	eval-mlogloss:0.25337
[104]	train-mlogloss:0.30659	eval-mlogloss:0.25203
[105]	train-mlogloss:0.30403	eval-mlogloss:0.24892
[106]	train-mlogloss:0.30272	eval-mlogloss:0.24746
[107]	train-mlogloss:0.30146	eval-mlogloss:0.24591
[108]	train-mlogloss:0.30023	eval-mlogloss:0.24463
[109]	train-mlogloss:0.29940	eval-mlogloss:0.24365
[110]	train-mlogloss:0.29911	eval-mlogloss:0.24311
[111]	train-mlogloss:0.29901	eval-mlogloss:0.24289
[112]	train-mlogloss:0.29662	eval-mlogloss:0.24020
[113]	train-mlogloss:0.29438	eval-mlogloss:0.23761
[114]	train-mlogloss:0.29400	eval-mlogloss:0.23716
[115]	train-mlogloss:0.29182	eval-mlogloss:0.23494
[116]	train-mlogloss:0.29079	eval-mlogloss:0.23360
[117]	train-mlogloss:0.28970	eval-mlogloss:0.23224
[118]	train-mlogloss:0.28759	eval-mlogloss:0.22992
[119]	train-mlogloss:0.28659	eval-mlogloss:0.22882
[120]	train-mlogloss:0.28646	eval-mlogloss:0.22867
[121]	train-mlogloss:0.28628	eval-mlogloss:0.22833
[122]	train-mlogloss:0.28605	eval-mlogloss:0.22810
[123]	train-mlogloss:0.28598	eval-mlogloss:0.22801
[124]	train-mlogloss:0.28596	eval-mlogloss:0.22799
[125]	train-mlogloss:0.28589	eval-mlogloss:0.22787
[126]	train-mlogloss:0.28580	eval-mlogloss:0.22781
[127]	train-mlogloss:0.28576	eval-mlogloss:0.22779
[128]	train-mlogloss:0.28578	eval-mlogloss:0.22778
[129]	train-mlogloss:0.28565	eval-mlogloss:0.22744
[130]	train-mlogloss:0.28470	eval-mlogloss:0.22620
[131]	train-mlogloss:0.28378	eval-mlogloss:0.22483
[132]	train-mlogloss:0.28308	eval-mlogloss:0.22398
[133]	train-mlogloss:0.28297	eval-mlogloss:0.22393
[134]	train-mlogloss:0.28292	eval-mlogloss:0.22381
[135]	train-mlogloss:0.28284	eval-mlogloss:0.22357
[136]	train-mlogloss:0.28251	eval-mlogloss:0.22314
[137]	train-mlogloss:0.28251	eval-mlogloss:0.22314
[138]	train-mlogloss:0.28051	eval-mlogloss:0.22105
[139]	train-mlogloss:0.28036	eval-mlogloss:0.22101
[140]	train-mlogloss:0.27950	eval-mlogloss:0.21986
[141]	train-mlogloss:0.27882	eval-mlogloss:0.21903
[142]	train-mlogloss:0.27883	eval-mlogloss:0.21905
[143]	train-mlogloss:0.27866	eval-mlogloss:0.21888
[144]	train-mlogloss:0.27842	eval-mlogloss:0.21845
[145]	train-mlogloss:0.27830	eval-mlogloss:0.21829
[146]	train-mlogloss:0.27747	eval-mlogloss:0.21724
[147]	train-mlogloss:0.27718	eval-mlogloss:0.21662
[148]	train-mlogloss:0.27718	eval-mlogloss:0.21664
[149]	train-mlogloss:0.27691	eval-mlogloss:0.21620
[150]	train-mlogloss:0.27683	eval-mlogloss:0.21614
[151]	train-mlogloss:0.27653	eval-mlogloss:0.21577
[152]	train-mlogloss:0.27643	eval-mlogloss:0.21567
[153]	train-mlogloss:0.27620	eval-mlogloss:0.21514
[154]	train-mlogloss:0.27605	eval-mlogloss:0.21496
[155]	train-mlogloss:0.27598	eval-mlogloss:0.21491
[156]	train-mlogloss:0.27506	eval-mlogloss:0.21376
[157]	train-mlogloss:0.27505	eval-mlogloss:0.21372
[158]	train-mlogloss:0.27502	eval-mlogloss:0.21377
[159]	train-mlogloss:0.27492	eval-mlogloss:0.21345
[160]	train-mlogloss:0.27485	eval-mlogloss:0.21320
[161]	train-mlogloss:0.27480	eval-mlogloss:0.21315
[162]	train-mlogloss:0.27473	eval-mlogloss:0.21293
[163]	train-mlogloss:0.27469	eval-mlogloss:0.21289
[164]	train-mlogloss:0.27358	eval-mlogloss:0.21179
[165]	train-mlogloss:0.27351	eval-mlogloss:0.21156
[166]	train-mlogloss:0.27318	eval-mlogloss:0.21111
[167]	train-mlogloss:0.27283	eval-mlogloss:0.21075
[168]	train-mlogloss:0.27274	eval-mlogloss:0.21070
[169]	train-mlogloss:0.27263	eval-mlogloss:0.21032
[170]	train-mlogloss:0.27259	eval-mlogloss:0.21029
[171]	train-mlogloss:0.27172	eval-mlogloss:0.20909
[172]	train-mlogloss:0.27097	eval-mlogloss:0.20803
[173]	train-mlogloss:0.27092	eval-mlogloss:0.20801
[174]	train-mlogloss:0.27082	eval-mlogloss:0.20796
[175]	train-mlogloss:0.27074	eval-mlogloss:0.20766
[176]	train-mlogloss:0.27063	eval-mlogloss:0.20759
[177]	train-mlogloss:0.27061	eval-mlogloss:0.20765
[178]	train-mlogloss:0.27055	eval-mlogloss:0.20761
[179]	train-mlogloss:0.27046	eval-mlogloss:0.20755
[180]	train-mlogloss:0.27042	eval-mlogloss:0.20750
[181]	train-mlogloss:0.27040	eval-mlogloss:0.20744
[182]	train-mlogloss:0.27017	eval-mlogloss:0.20716
[183]	train-mlogloss:0.27010	eval-mlogloss:0.20692
[184]	train-mlogloss:0.27007	eval-mlogloss:0.20685
[185]	train-mlogloss:0.27005	eval-mlogloss:0.20689
[186]	train-mlogloss:0.26995	eval-mlogloss:0.20686
[187]	train-mlogloss:0.26990	eval-mlogloss:0.20682
[188]	train-mlogloss:0.26986	eval-mlogloss:0.20690
[189]	train-mlogloss:0.26975	eval-mlogloss:0.20650
[190]	train-mlogloss:0.26976	eval-mlogloss:0.20651
[191]	train-mlogloss:0.26972	eval-mlogloss:0.20646
[192]	train-mlogloss:0.26968	eval-mlogloss:0.20633
[193]	train-mlogloss:0.26960	eval-mlogloss:0.20629
[194]	train-mlogloss:0.26950	eval-mlogloss:0.20628
[195]	train-mlogloss:0.26944	eval-mlogloss:0.20624
[196]	train-mlogloss:0.26940	eval-mlogloss:0.20621
[197]	train-mlogloss:0.26933	eval-mlogloss:0.20618
[198]	train-mlogloss:0.26931	eval-mlogloss:0.20613
[199]	train-mlogloss:0.26855	eval-mlogloss:0.20537
[200]	train-mlogloss:0.26852	eval-mlogloss:0.20535
[201]	train-mlogloss:0.26851	eval-mlogloss:0.20538
[202]	train-mlogloss:0.26842	eval-mlogloss:0.20535
[203]	train-mlogloss:0.26824	eval-mlogloss:0.20515
[204]	train-mlogloss:0.26815	eval-mlogloss:0.20510
[205]	train-mlogloss:0.26743	eval-mlogloss:0.20397
[206]	train-mlogloss:0.26744	eval-mlogloss:0.20396
[207]	train-mlogloss:0.26741	eval-mlogloss:0.20394
[208]	train-mlogloss:0.26734	eval-mlogloss:0.20392
[209]	train-mlogloss:0.26735	eval-mlogloss:0.20392
[210]	train-mlogloss:0.26729	eval-mlogloss:0.20390
[211]	train-mlogloss:0.26721	eval-mlogloss:0.20386
[212]	train-mlogloss:0.26713	eval-mlogloss:0.20382
[213]	train-mlogloss:0.26656	eval-mlogloss:0.20298
[214]	train-mlogloss:0.26648	eval-mlogloss:0.20296
[215]	train-mlogloss:0.26645	eval-mlogloss:0.20291
[216]	train-mlogloss:0.26645	eval-mlogloss:0.20291
[217]	train-mlogloss:0.26639	eval-mlogloss:0.20283
[218]	train-mlogloss:0.26628	eval-mlogloss:0.20264
[219]	train-mlogloss:0.26553	eval-mlogloss:0.20178
[220]	train-mlogloss:0.26553	eval-mlogloss:0.20177
[221]	train-mlogloss:0.26547	eval-mlogloss:0.20172
[222]	train-mlogloss:0.26544	eval-mlogloss:0.20170
[223]	train-mlogloss:0.26468	eval-mlogloss:0.20085
[224]	train-mlogloss:0.26460	eval-mlogloss:0.20080
[225]	train-mlogloss:0.26455	eval-mlogloss:0.20060
[226]	train-mlogloss:0.26445	eval-mlogloss:0.20054
[227]	train-mlogloss:0.26441	eval-mlogloss:0.20042
[228]	train-mlogloss:0.26438	eval-mlogloss:0.20036
[229]	train-mlogloss:0.26438	eval-mlogloss:0.20036
[230]	train-mlogloss:0.26420	eval-mlogloss:0.20008
[231]	train-mlogloss:0.26416	eval-mlogloss:0.20001
[232]	train-mlogloss:0.26410	eval-mlogloss:0.20000
[233]	train-mlogloss:0.26404	eval-mlogloss:0.19996
[234]	train-mlogloss:0.26404	eval-mlogloss:0.19997
[235]	train-mlogloss:0.26399	eval-mlogloss:0.19995
[236]	train-mlogloss:0.26393	eval-mlogloss:0.19975
[237]	train-mlogloss:0.26387	eval-mlogloss:0.19953
[238]	train-mlogloss:0.26366	eval-mlogloss:0.19899
[239]	train-mlogloss:0.26363	eval-mlogloss:0.19894
[240]	train-mlogloss:0.26364	eval-mlogloss:0.19892
[241]	train-mlogloss:0.26359	eval-mlogloss:0.19872
[242]	train-mlogloss:0.26354	eval-mlogloss:0.19870
[243]	train-mlogloss:0.26290	eval-mlogloss:0.19780
[244]	train-mlogloss:0.26281	eval-mlogloss:0.19776
[245]	train-mlogloss:0.26273	eval-mlogloss:0.19749
[246]	train-mlogloss:0.26271	eval-mlogloss:0.19746
[247]	train-mlogloss:0.26269	eval-mlogloss:0.19752
[248]	train-mlogloss:0.26264	eval-mlogloss:0.19731
[249]	train-mlogloss:0.26262	eval-mlogloss:0.19736
[250]	train-mlogloss:0.26262	eval-mlogloss:0.19736
[251]	train-mlogloss:0.26255	eval-mlogloss:0.19732
[252]	train-mlogloss:0.26243	eval-mlogloss:0.19716
[253]	train-mlogloss:0.26239	eval-mlogloss:0.19710
[254]	train-mlogloss:0.26232	eval-mlogloss:0.19704
[255]	train-mlogloss:0.26229	eval-mlogloss:0.19697

[I 2026-08-19 16:57:36,035] Trial 21 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.04484	eval-mlogloss:1.04423
[1]	train-mlogloss:0.99323	eval-mlogloss:0.99171
[2]	train-mlogloss:0.94396	eval-mlogloss:0.93849
[3]	train-mlogloss:0.89923	eval-mlogloss:0.89139

[I 2026-08-19 16:57:36,062] Trial 22 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.99341	eval-mlogloss:0.98985

[I 2026-08-19 16:57:36,090] Trial 23 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08911	eval-mlogloss:1.09015
[1]	train-mlogloss:1.08013	eval-mlogloss:1.08080
[2]	train-mlogloss:1.06956	eval-mlogloss:1.06989
[3]	train-mlogloss:1.06146	eval-mlogloss:1.06156
[4]	train-mlogloss:1.05234	eval-mlogloss:1.05254
[5]	train-mlogloss:1.04450	eval-mlogloss:1.04415
[6]	train-mlogloss:1.03642	eval-mlogloss:1.03593
[7]	train-mlogloss:1.02862	eval-mlogloss:1.02736
[8]	train-mlogloss:1.01865	eval-mlogloss:1.01721
[9]	train-mlogloss:1.00881	eval-mlogloss:1.00706
[10]	train-mlogloss:1.00131	eval-mlogloss:0.99845
[11]	train-mlogloss:0.99216	eval-mlogloss:0.98812
[12]	train-mlogloss:0.98300	eval-mlogloss:0.97838
[13]	train-mlogloss:0.97668	eval-mlogloss:0.97188
[14]	train-mlogloss:0.97013	eval-mlogloss:0.96490
[15]	train-mlogloss:0.96140	eval-mlogloss:0.95565
[16]	train-mlogloss:0.95282	eval-mlogloss:0.94686
[17]	train-mlogloss:0.94488	eval-mlogloss:0.93857
[18]	train-mlogloss:0.93670	eval-mlogloss:0.92963
[19]	train-mlogloss:0.92978	eval-mlogloss:0.92227
[20]	train-mlogloss:0.92134	eval-mlogloss:0.91328
[21]	train-mlogloss:0.91308	eval-mlogloss:0.90448
[22]	train-mlogloss:0.90590	eval-mlogloss:0.89691
[23]	train-mlogloss:0.89908	eval-mlogloss:0.89043
[24]	train-mlogloss:0.89273	eval-mlogloss:0.88304
[25]	train-mlogloss:0.88545	eval-mlogloss:0.87563
[26]	train-mlogloss:0.87825	eval-mlogloss:0.86796
[27]	train-mlogloss:0.87005	eval-mlogloss:0.85949
[28]	train-mlogloss:0.86054	eval-mlogloss:0.84929
[29]	train-mlogloss:0.85427	eval-mlogloss:0.84254
[30]	train-mlogloss:0.84874	eval-mlogloss:0.83640
[31]	train-mlogloss:0.84115	eval-mlogloss:0.82875
[32]	train-mlogloss:0.83483	eval-mlogloss:0.82187
[33]	train-mlogloss:0.82753	eval-mlogloss:0.81399
[34]	train-mlogloss:0.82204	eval-mlogloss:0.80793
[35]	train-mlogloss:0.81565	eval-mlogloss:0.80057
[36]	train-mlogloss:0.81064	eval-mlogloss:0.79568
[37]	train-mlogloss:0.80409	eval-mlogloss:0.78880
[38]	train-mlogloss:0.79626	eval-mlogloss:0.78019
[39]	train-mlogloss:0.79186	eval-mlogloss:0.77535
[40]	train-mlogloss:0.78581	eval-mlogloss:0.76863
[41]	train-mlogloss:0.77987	eval-mlogloss:0.76248
[42]	train-mlogloss:0.77451	eval-mlogloss:0.75749
[43]	train-mlogloss:0.76943	eval-mlogloss:0.75219
[44]	train-mlogloss:0.76351	eval-mlogloss:0.74674
[45]	train-mlogloss:0.75837	eval-mlogloss:0.74125
[46]	train-mlogloss:0.75296	eval-mlogloss:0.73504
[47]	train-mlogloss:0.74755	eval-mlogloss:0.72942
[48]	train-mlogloss:0.74049	eval-mlogloss:0.72276
[49]	train-mlogloss:0.73525	eval-mlogloss:0.71707
[50]	train-mlogloss:0.73089	eval-mlogloss:0.71251
[51]	train-mlogloss:0.72673	eval-mlogloss:0.70833
[52]	train-mlogloss:0.71967	eval-mlogloss:0.70091
[53]	train-mlogloss:0.71507	eval-mlogloss:0.69598
[54]	train-mlogloss:0.70949	eval-mlogloss:0.69025
[55]	train-mlogloss:0.70379	eval-mlogloss:0.68370
[56]	train-mlogloss:0.70005	eval-mlogloss:0.67970
[57]	train-mlogloss:0.69588	eval-mlogloss:0.67523
[58]	train-mlogloss:0.69075	eval-mlogloss:0.66943
[59]	train-mlogloss:0.68609	eval-mlogloss:0.66426
[60]	train-mlogloss:0.68006	eval-mlogloss:0.65770
[61]	train-mlogloss:0.67600	eval-mlogloss:0.65354
[62]	train-mlogloss:0.67192	eval-mlogloss:0.64871
[63]	train-mlogloss:0.66786	eval-mlogloss:0.64472
[64]	train-mlogloss:0.66170	eval-mlogloss:0.63817
[65]	train-mlogloss:0.65825	eval-mlogloss:0.63408
[66]	train-mlogloss:0.65421	eval-mlogloss:0.62962
[67]	train-mlogloss:0.65114	eval-mlogloss:0.62638
[68]	train-mlogloss:0.64759	eval-mlogloss:0.62277
[69]	train-mlogloss:0.64527	eval-mlogloss:0.62012
[70]	train-mlogloss:0.64190	eval-mlogloss:0.61651
[71]	train-mlogloss:0.63879	eval-mlogloss:0.61301
[72]	train-mlogloss:0.63420	eval-mlogloss:0.60805
[73]	train-mlogloss:0.63138	eval-mlogloss:0.60488
[74]	train-mlogloss:0.62714	eval-mlogloss:0.60031
[75]	train-mlogloss:0.62393	eval-mlogloss:0.59682
[76]	train-mlogloss:0.61971	eval-mlogloss:0.59236
[77]	train-mlogloss:0.61611	eval-mlogloss:0.58825
[78]	train-mlogloss:0.61270	eval-mlogloss:0.58473
[79]	train-mlogloss:0.60966	eval-mlogloss:0.58146
[80]	train-mlogloss:0.60786	eval-mlogloss:0.57940
[81]	train-mlogloss:0.60577	eval-mlogloss:0.57737
[82]	train-mlogloss:0.60163	eval-mlogloss:0.57242
[83]	train-mlogloss:0.59813	eval-mlogloss:0.56874
[84]	train-mlogloss:0.59568	eval-mlogloss:0.56646
[85]	train-mlogloss:0.59419	eval-mlogloss:0.56490
[86]	train-mlogloss:0.59062	eval-mlogloss:0.56075
[87]	train-mlogloss:0.58903	eval-mlogloss:0.55925
[88]	train-mlogloss:0.58699	eval-mlogloss:0.55704
[89]	train-mlogloss:0.58363	eval-mlogloss:0.55364
[90]	train-mlogloss:0.58003	eval-mlogloss:0.54976
[91]	train-mlogloss:0.57713	eval-mlogloss:0.54673
[92]	train-mlogloss:0.57422	eval-mlogloss:0.54346
[93]	train-mlogloss:0.57139	eval-mlogloss:0.54053
[94]	train-mlogloss:0.56881	eval-mlogloss:0.53828
[95]	train-mlogloss:0.56606	eval-mlogloss:0.53501
[96]	train-mlogloss:0.56310	eval-mlogloss:0.53177
[97]	train-mlogloss:0.55936	eval-mlogloss:0.52809
[98]	train-mlogloss:0.55646	eval-mlogloss:0.52523
[99]	train-mlogloss:0.55496	eval-mlogloss:0.52352
[100]	train-mlogloss:0.55247	eval-mlogloss:0.52086
[101]	train-mlogloss:0.54953	eval-mlogloss:0.51785
[102]	train-mlogloss:0.54935	eval-mlogloss:0.51754
[103]	train-mlogloss:0.54757	eval-mlogloss:0.51557
[104]	train-mlogloss:0.54402	eval-mlogloss:0.51175
[105]	train-mlogloss:0.54029	eval-mlogloss:0.50763
[106]	train-mlogloss:0.53760	eval-mlogloss:0.50474
[107]	train-mlogloss:0.53580	eval-mlogloss:0.50255
[108]	train-mlogloss:0.53391	eval-mlogloss:0.50064
[109]	train-mlogloss:0.53292	eval-mlogloss:0.49962
[110]	train-mlogloss:0.53237	eval-mlogloss:0.49890
[111]	train-mlogloss:0.53086	eval-mlogloss:0.49695
[112]	train-mlogloss:0.52777	eval-mlogloss:0.49353
[113]	train-mlogloss:0.52501	eval-mlogloss:0.49021
[114]	train-mlogloss:0.52264	eval-mlogloss:0.48769
[115]	train-mlogloss:0.51882	eval-mlogloss:0.48355
[116]	train-mlogloss:0.51654	eval-mlogloss:0.48135
[117]	train-mlogloss:0.51382	eval-mlogloss:0.47827
[118]	train-mlogloss:0.51068	eval-mlogloss:0.47501
[119]	train-mlogloss:0.50913	eval-mlogloss:0.47318
[120]	train-mlogloss:0.50763	eval-mlogloss:0.47160
[121]	train-mlogloss:0.50698	eval-mlogloss:0.47087
[122]	train-mlogloss:0.50540	eval-mlogloss:0.46918
[123]	train-mlogloss:0.50533	eval-mlogloss:0.46921
[124]	train-mlogloss:0.50267	eval-mlogloss:0.46646
[125]	train-mlogloss:0.50132	eval-mlogloss:0.46509
[126]	train-mlogloss:0.50100	eval-mlogloss:0.46487
[127]	train-mlogloss:0.50046	eval-mlogloss:0.46419
[128]	train-mlogloss:0.49887	eval-mlogloss:0.46235
[129]	train-mlogloss:0.49852	eval-mlogloss:0.46197
[130]	train-mlogloss:0.49552	eval-mlogloss:0.45879
[131]	train-mlogloss:0.49397	eval-mlogloss:0.45661
[132]	train-mlogloss:0.49257	eval-mlogloss:0.45480
[133]	train-mlogloss:0.48976	eval-mlogloss:0.45186
[134]	train-mlogloss:0.48865	eval-mlogloss:0.45058
[135]	train-mlogloss:0.48699	eval-mlogloss:0.44872
[136]	train-mlogloss:0.48459	eval-mlogloss:0.44582
[137]	train-mlogloss:0.48200	eval-mlogloss:0.44307
[138]	train-mlogloss:0.47951	eval-mlogloss:0.44036
[139]	train-mlogloss:0.47882	eval-mlogloss:0.43966
[140]	train-mlogloss:0.47682	eval-mlogloss:0.43714
[141]	train-mlogloss:0.47654	eval-mlogloss:0.43670
[142]	train-mlogloss:0.47655	eval-mlogloss:0.43674
[143]	train-mlogloss:0.47615	eval-mlogloss:0.43629
[144]	train-mlogloss:0.47488	eval-mlogloss:0.43474
[145]	train-mlogloss:0.47445	eval-mlogloss:0.43425
[146]	train-mlogloss:0.47246	eval-mlogloss:0.43184
[147]	train-mlogloss:0.47054	eval-mlogloss:0.42951
[148]	train-mlogloss:0.46946	eval-mlogloss:0.42826
[149]	train-mlogloss:0.46902	eval-mlogloss:0.42751
[150]	train-mlogloss:0.46873	eval-mlogloss:0.42707
[151]	train-mlogloss:0.46750	eval-mlogloss:0.42574
[152]	train-mlogloss:0.46722	eval-mlogloss:0.42544
[153]	train-mlogloss:0.46541	eval-mlogloss:0.42328
[154]	train-mlogloss:0.46496	eval-mlogloss:0.42270
[155]	train-mlogloss:0.46393	eval-mlogloss:0.42154
[156]	train-mlogloss:0.46275	eval-mlogloss:0.42009
[157]	train-mlogloss:0.46152	eval-mlogloss:0.41872
[158]	train-mlogloss:0.46045	eval-mlogloss:0.41757
[159]	train-mlogloss:0.46031	eval-mlogloss:0.41723
[160]	train-mlogloss:0.46014	eval-mlogloss:0.41701
[161]	train-mlogloss:0.45870	eval-mlogloss:0.41489
[162]	train-mlogloss:0.45851	eval-mlogloss:0.41446
[163]	train-mlogloss:0.45782	eval-mlogloss:0.41390
[164]	train-mlogloss:0.45541	eval-mlogloss:0.41136
[165]	train-mlogloss:0.45408	eval-mlogloss:0.40952
[166]	train-mlogloss:0.45379	eval-mlogloss:0.40913
[167]	train-mlogloss:0.45262	eval-mlogloss:0.40789
[168]	train-mlogloss:0.45237	eval-mlogloss:0.40779
[169]	train-mlogloss:0.45217	eval-mlogloss:0.40732
[170]	train-mlogloss:0.45190	eval-mlogloss:0.40707
[171]	train-mlogloss:0.45164	eval-mlogloss:0.40691
[172]	train-mlogloss:0.45042	eval-mlogloss:0.40537
[173]	train-mlogloss:0.44919	eval-mlogloss:0.40395
[174]	train-mlogloss:0.44909	eval-mlogloss:0.40386
[175]	train-mlogloss:0.44792	eval-mlogloss:0.40230
[176]	train-mlogloss:0.44762	eval-mlogloss:0.40193
[177]	train-mlogloss:0.44738	eval-mlogloss:0.40165
[178]	train-mlogloss:0.44644	eval-mlogloss:0.40053
[179]	train-mlogloss:0.44615	eval-mlogloss:0.40020
[180]	train-mlogloss:0.44612	eval-mlogloss:0.40016
[181]	train-mlogloss:0.44603	eval-mlogloss:0.39988
[182]	train-mlogloss:0.44465	eval-mlogloss:0.39856
[183]	train-mlogloss:0.44347	eval-mlogloss:0.39742
[184]	train-mlogloss:0.44233	eval-mlogloss:0.39600
[185]	train-mlogloss:0.44224	eval-mlogloss:0.39590
[186]	train-mlogloss:0.44217	eval-mlogloss:0.39591
[187]	train-mlogloss:0.44103	eval-mlogloss:0.39465
[188]	train-mlogloss:0.44088	eval-mlogloss:0.39429
[189]	train-mlogloss:0.44069	eval-mlogloss:0.39383
[190]	train-mlogloss:0.44053	eval-mlogloss:0.39373
[191]	train-mlogloss:0.44022	eval-mlogloss:0.39314
[192]	train-mlogloss:0.43997	eval-mlogloss:0.39287
[193]	train-mlogloss:0.43989	eval-mlogloss:0.39279
[194]	train-mlogloss:0.43974	eval-mlogloss:0.39245
[195]	train-mlogloss:0.43969	eval-mlogloss:0.39243
[196]	train-mlogloss:0.43965	eval-mlogloss:0.39247
[197]	train-mlogloss:0.43960	eval-mlogloss:0.39253
[198]	train-mlogloss:0.43936	eval-mlogloss:0.39216
[199]	train-mlogloss:0.43745	eval-mlogloss:0.39010
[200]	train-mlogloss:0.43745	eval-mlogloss:0.39011
[201]	train-mlogloss:0.43734	eval-mlogloss:0.39003
[202]	train-mlogloss:0.43729	eval-mlogloss:0.39010
[203]	train-mlogloss:0.43714	eval-mlogloss:0.38999
[204]	train-mlogloss:0.43705	eval-mlogloss:0.38997
[205]	train-mlogloss:0.43611	eval-mlogloss:0.38890
[206]	train-mlogloss:0.43597	eval-mlogloss:0.38870
[207]	train-mlogloss:0.43580	eval-mlogloss:0.38858
[208]	train-mlogloss:0.43561	eval-mlogloss:0.38837
[209]	train-mlogloss:0.43417	eval-mlogloss:0.38653
[210]	train-mlogloss:0.43412	eval-mlogloss:0.38651
[211]	train-mlogloss:0.43290	eval-mlogloss:0.38513
[212]	train-mlogloss:0.43282	eval-mlogloss:0.38505
[213]	train-mlogloss:0.43197	eval-mlogloss:0.38383
[214]	train-mlogloss:0.43191	eval-mlogloss:0.38379
[215]	train-mlogloss:0.43092	eval-mlogloss:0.38265
[216]	train-mlogloss:0.43075	eval-mlogloss:0.38247
[217]	train-mlogloss:0.43070	eval-mlogloss:0.38240
[218]	train-mlogloss:0.43055	eval-mlogloss:0.38201
[219]	train-mlogloss:0.42937	eval-mlogloss:0.38069
[220]	train-mlogloss:0.42935	eval-mlogloss:0.38067
[221]	train-mlogloss:0.42927	eval-mlogloss:0.38058
[222]	train-mlogloss:0.42847	eval-mlogloss:0.37977
[223]	train-mlogloss:0.42739	eval-mlogloss:0.37857
[224]	train-mlogloss:0.42732	eval-mlogloss:0.37848
[225]	train-mlogloss:0.42732	eval-mlogloss:0.37846
[226]	train-mlogloss:0.42611	eval-mlogloss:0.37732
[227]	train-mlogloss:0.42600	eval-mlogloss:0.37724
[228]	train-mlogloss:0.42506	eval-mlogloss:0.37597
[229]	train-mlogloss:0.42475	eval-mlogloss:0.37537
[230]	train-mlogloss:0.42452	eval-mlogloss:0.37498
[231]	train-mlogloss:0.42432	eval-mlogloss:0.37477
[232]	train-mlogloss:0.42335	eval-mlogloss:0.37373
[233]	train-mlogloss:0.42323	eval-mlogloss:0.37351
[234]	train-mlogloss:0.42323	eval-mlogloss:0.37354
[235]	train-mlogloss:0.42313	eval-mlogloss:0.37344
[236]	train-mlogloss:0.42210	eval-mlogloss:0.37207
[237]	train-mlogloss:0.42188	eval-mlogloss:0.37185
[238]	train-mlogloss:0.42176	eval-mlogloss:0.37150
[239]	train-mlogloss:0.42173	eval-mlogloss:0.37146
[240]	train-mlogloss:0.42177	eval-mlogloss:0.37148
[241]	train-mlogloss:0.42068	eval-mlogloss:0.36997
[242]	train-mlogloss:0.42064	eval-mlogloss:0.36995
[243]	train-mlogloss:0.42056	eval-mlogloss:0.36976
[244]	train-mlogloss:0.42047	eval-mlogloss:0.36974
[245]	train-mlogloss:0.42046	eval-mlogloss:0.36972
[246]	train-mlogloss:0.42041	eval-mlogloss:0.36972
[247]	train-mlogloss:0.42035	eval-mlogloss:0.36977
[248]	train-mlogloss:0.42021	eval-mlogloss:0.36940
[249]	train-mlogloss:0.42021	eval-mlogloss:0.36939
[250]	train-mlogloss:0.41980	eval-mlogloss:0.36865
[251]	train-mlogloss:0.41973	eval-mlogloss:0.36864
[252]	train-mlogloss:0.41944	eval-mlogloss:0.36833
[253]	train-mlogloss:0.41827	eval-mlogloss:0.36681
[254]	train-mlogloss:0.41819	eval-mlogloss:0.36677
[255]	train-mlogloss:0.41721	eval-mlogloss:0.36575
[256]	train-mlogloss:0.41716	eval-mlogloss:0.36572
[257]	train-mlogloss:0.41708	eval-mlogloss:0.36562
[258]	train-mlogloss:0.41699	eval-mlogloss:0.36556
[259]	train-mlogloss:0.41687	eval-mlogloss:0.36550
[260]	train-mlogloss:0.41680	eval-mlogloss:0.36537
[261]	train-mlogloss:0.41674	eval-mlogloss:0.36528
[262]	train-mlogloss:0.41660	eval-mlogloss:0.36498
[263]	train-mlogloss:0.41644	eval-mlogloss:0.36487
[264]	train-mlogloss:0.41557	eval-mlogloss:0.36388
[265]	train-mlogloss:0.41552	eval-mlogloss:0.36386
[266]	train-mlogloss:0.41479	eval-mlogloss:0.36302
[267]	train-mlogloss:0.41472	eval-mlogloss:0.36295
[268]	train-mlogloss:0.41476	eval-mlogloss:0.36300
[269]	train-mlogloss:0.41472	eval-mlogloss:0.36298
[270]	train-mlogloss:0.41379	eval-mlogloss:0.36175
[271]	train-mlogloss:0.41379	eval-mlogloss:0.36178
[272]	train-mlogloss:0.41360	eval-mlogloss:0.36131
[273]	train-mlogloss:0.41342	eval-mlogloss:0.36111
[274]	train-mlogloss:0.41334	eval-mlogloss:0.36102
[275]	train-mlogloss:0.41198	eval-mlogloss:0.35962
[276]	train-mlogloss:0.41198	eval-mlogloss:0.35960
[277]	train-mlogloss:0.41198	eval-mlogloss:0.35958
[278]	train-mlogloss:0.41199	eval-mlogloss:0.35954
[279]	train-mlogloss:0.41198	eval-mlogloss:0.35955
[280]	train-mlogloss:0.41198	eval-mlogloss:0.35957
[281]	train-mlogloss:0.41181	eval-mlogloss:0.35940
[282]	train-mlogloss:0.41181	eval-mlogloss:0.35937
[283]	train-mlogloss:0.41161	eval-mlogloss:0.35915
[284]	train-mlogloss:0.41112	eval-mlogloss:0.35869
[285]	train-mlogloss:0.41114	eval-mlogloss:0.35871
[286]	train-mlogloss:0.41113	eval-mlogloss:0.35873
[287]	train-mlogloss:0.41108	eval-mlogloss:0.35862
[288]	train-mlogloss:0.41100	eval-mlogloss:0.35854
[289]	train-mlogloss:0.41091	eval-mlogloss:0.35847
[290]	train-mlogloss:0.41081	eval-mlogloss:0.35822
[291]	train-mlogloss:0.41077	eval-mlogloss:0.35821
[292]	train-mlogloss:0.40980	eval-mlogloss:0.35671
[293]	train-mlogloss:0.40917	eval-mlogloss:0.35610
[294]	train-mlogloss:0.40912	eval-mlogloss:0.35606
[295]	train-mlogloss:0.40907	eval-mlogloss:0.35602
[296]	train-mlogloss:0.40899	eval-mlogloss:0.35599
[297]	train-mlogloss:0.40890	eval-mlogloss:0.35578
[298]	train-mlogloss:0.40889	eval-mlogloss:0.35580
[299]	train-mlogloss:0.40883	eval-mlogloss:0.35578

[I 2026-08-19 16:57:36,793] Trial 24 finished with value: 0.9666666666666667 and parameters: {'lambda': 0.0014219108905340375, 'alpha': 1.427105512905085e-06, 'eta': 0.010842736500987618, 'gamma': 0.11575615048164488, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.5343838906057415, 'colsample_bytree': 0.7111954276053182}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05563	eval-mlogloss:1.05406
[1]	train-mlogloss:1.01550	eval-mlogloss:1.01342
[2]	train-mlogloss:0.97575	eval-mlogloss:0.97031
[3]	train-mlogloss:0.94714	eval-mlogloss:0.94046

[I 2026-08-19 16:57:36,819] Trial 25 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.94013	eval-mlogloss:0.94017

[I 2026-08-19 16:57:36,843] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05400	eval-mlogloss:1.05186
[1]	train-mlogloss:1.01651	eval-mlogloss:1.01487
[2]	train-mlogloss:0.98000	eval-mlogloss:0.97689
[3]	train-mlogloss:0.95153	eval-mlogloss:0.94664

[I 2026-08-19 16:57:36,871] Trial 27 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08402	eval-mlogloss:1.08603
[1]	train-mlogloss:1.06679	eval-mlogloss:1.06849
[2]	train-mlogloss:1.05821	eval-mlogloss:1.06030
[3]	train-mlogloss:1.05029	eval-mlogloss:1.05271
[4]	train-mlogloss:1.03716	eval-mlogloss:1.03977
[5]	train-mlogloss:1.02904	eval-mlogloss:1.03166
[6]	train-mlogloss:1.01359	eval-mlogloss:1.01476
[7]	train-mlogloss:1.00524	eval-mlogloss:1.00653
[8]	train-mlogloss:0.99404	eval-mlogloss:0.99534
[9]	train-mlogloss:0.98094	eval-mlogloss:0.98179
[10]	train-mlogloss:0.97735	eval-mlogloss:0.97821
[11]	train-mlogloss:0.96560	eval-mlogloss:0.96560
[12]	train-mlogloss:0.95873	eval-mlogloss:0.95863
[13]	train-mlogloss:0.94851	eval-mlogloss:0.94782
[14]	train-mlogloss:0.94183	eval-mlogloss:0.94048
[15]	train-mlogloss:0.93325	eval-mlogloss:0.93193

[I 2026-08-19 16:57:36,928] Trial 28 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:0.77501	eval-mlogloss:0.75324

[I 2026-08-19 16:57:36,951] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84522	eval-mlogloss:0.84213

[I 2026-08-19 16:57:36,974] Trial 30 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05788	eval-mlogloss:1.05902
[1]	train-mlogloss:1.01871	eval-mlogloss:1.01915
[2]	train-mlogloss:0.98033	eval-mlogloss:0.97773
[3]	train-mlogloss:0.94594	eval-mlogloss:0.94136

[I 2026-08-19 16:57:37,000] Trial 31 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08556	eval-mlogloss:1.08684
[1]	train-mlogloss:1.07293	eval-mlogloss:1.07399
[2]	train-mlogloss:1.06039	eval-mlogloss:1.06047
[3]	train-mlogloss:1.04837	eval-mlogloss:1.04788
[4]	train-mlogloss:1.03621	eval-mlogloss:1.03518
[5]	train-mlogloss:1.02412	eval-mlogloss:1.02231
[6]	train-mlogloss:1.01272	eval-mlogloss:1.01008
[7]	train-mlogloss:1.00141	eval-mlogloss:0.99813
[8]	train-mlogloss:0.98999	eval-mlogloss:0.98631
[9]	train-mlogloss:0.98012	eval-mlogloss:0.97667
[10]	train-mlogloss:0.96957	eval-mlogloss:0.96590
[11]	train-mlogloss:0.95885	eval-mlogloss:0.95446
[12]	train-mlogloss:0.94815	eval-mlogloss:0.94325
[13]	train-mlogloss:0.93757	eval-mlogloss:0.93203
[14]	train-mlogloss:0.92691	eval-mlogloss:0.92087
[15]	train-mlogloss:0.91660	eval-mlogloss:0.91006

[I 2026-08-19 16:57:37,052] Trial 32 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.03725	eval-mlogloss:1.03265

[I 2026-08-19 16:57:37,077] Trial 33 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05745	eval-mlogloss:1.05925
[1]	train-mlogloss:1.01649	eval-mlogloss:1.01669
[2]	train-mlogloss:0.97883	eval-mlogloss:0.97685
[3]	train-mlogloss:0.94532	eval-mlogloss:0.94104

[I 2026-08-19 16:57:37,108] Trial 34 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.97771	eval-mlogloss:0.97990

[I 2026-08-19 16:57:37,131] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02170	eval-mlogloss:1.01812

[I 2026-08-19 16:57:37,156] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83542	eval-mlogloss:0.82359

[I 2026-08-19 16:57:37,183] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06192	eval-mlogloss:1.06654
[1]	train-mlogloss:1.02207	eval-mlogloss:1.02525
[2]	train-mlogloss:1.00127	eval-mlogloss:1.00701
[3]	train-mlogloss:0.98237	eval-mlogloss:0.99044

[I 2026-08-19 16:57:37,216] Trial 38 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.87870	eval-mlogloss:0.86690

[I 2026-08-19 16:57:37,267] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.80540	eval-mlogloss:0.80575

[I 2026-08-19 16:57:37,296] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07108	eval-mlogloss:1.07147
[1]	train-mlogloss:1.04474	eval-mlogloss:1.04464
[2]	train-mlogloss:1.01877	eval-mlogloss:1.01665
[3]	train-mlogloss:0.99469	eval-mlogloss:0.99135

[I 2026-08-19 16:57:37,323] Trial 41 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03749	eval-mlogloss:1.03966

[I 2026-08-19 16:57:37,346] Trial 42 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06242	eval-mlogloss:1.06270
[1]	train-mlogloss:1.02776	eval-mlogloss:1.02620
[2]	train-mlogloss:0.99310	eval-mlogloss:0.98880
[3]	train-mlogloss:0.96115	eval-mlogloss:0.95537

[I 2026-08-19 16:57:37,379] Trial 43 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.89136	eval-mlogloss:0.87995

[I 2026-08-19 16:57:37,401] Trial 44 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08325	eval-mlogloss:1.08440
[1]	train-mlogloss:1.06839	eval-mlogloss:1.06927
[2]	train-mlogloss:1.05357	eval-mlogloss:1.05327
[3]	train-mlogloss:1.03951	eval-mlogloss:1.03843
[4]	train-mlogloss:1.02528	eval-mlogloss:1.02391
[5]	train-mlogloss:1.01143	eval-mlogloss:1.00920
[6]	train-mlogloss:0.99932	eval-mlogloss:0.99623
[7]	train-mlogloss:0.99098	eval-mlogloss:0.98788
[8]	train-mlogloss:0.97766	eval-mlogloss:0.97410
[9]	train-mlogloss:0.96454	eval-mlogloss:0.96061
[10]	train-mlogloss:0.95526	eval-mlogloss:0.95115
[11]	train-mlogloss:0.94283	eval-mlogloss:0.93788
[12]	train-mlogloss:0.93336	eval-mlogloss:0.92787
[13]	train-mlogloss:0.92557	eval-mlogloss:0.91972
[14]	train-mlogloss:0.91604	eval-mlogloss:0.90952
[15]	train-mlogloss:0.90438	eval-mlogloss:0.89681

[I 2026-08-19 16:57:37,453] Trial 45 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.04617	eval-mlogloss:1.04538

[I 2026-08-19 16:57:37,477] Trial 46 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00143	eval-mlogloss:0.99752

[I 2026-08-19 16:57:37,505] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03150	eval-mlogloss:1.03163

[I 2026-08-19 16:57:37,528] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97982	eval-mlogloss:0.97548

[I 2026-08-19 16:57:37,551] Trial 49 pruned. Trial was pruned at iteration 1.

Best trial: {'lambda': 0.00026044898401805317, 'alpha': 2.0029303880783146e-06, 'eta': 0.22585484883249554, 'gamma': 0.22457657025748454, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8081496973474069, 'colsample_bytree': 0.7378646224969284}
Best accuracy: 1.0

In [39]:
from optuna.visualization import plot_intermediate_values
# Plot intermediate values during the trials
plot_intermediate_values(study).show()