In [1]:
import pandas as pd
import requests

In [4]:
response = requests.get(
    "https://api.themoviedb.org/3/movie/top_rated",
    params={
        "api_key": "8265bd1679663a7ea12ac168da84d2e8",
        "language": "en-US",
        "page": 1,
    },
    timeout=10,
)
response.raise_for_status()
movies = response.json().get("results", [])
df = pd.DataFrame(movies)
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,28.6090,/sr1Yoj6XLPTWYcbDoBy67xivW4I.jpg,2026-03-12,False,False,9.048,312
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",68.9492,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.920,1967
2,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,59.5022,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.726,30798
3,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",134.6749,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.704,3601
4,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",28.5584,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.687,23184

In [5]:
temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [6]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,28.6090,/sr1Yoj6XLPTWYcbDoBy67xivW4I.jpg,2026-03-12,False,False,9.048,312
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",68.9492,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.920,1967
2,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,59.5022,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.726,30798
3,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",134.6749,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.704,3601
4,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",28.5584,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.687,23184

In [7]:
df = pd.DataFrame()

In [8]:
df

Empty DataFrame
Columns: []
Index: []

In [11]:
import time
import requests
import pandas as pd

session = requests.Session()
adapter = requests.adapters.HTTPAdapter(max_retries=3)
session.mount("https://", adapter)
session.mount("http://", adapter)

all_pages = []
max_retries = 3

for page in range(1, 429):
    response = None

    for attempt in range(max_retries):
        try:
            response = session.get(
                "https://api.themoviedb.org/3/movie/top_rated",
                params={
                    "api_key": "8265bd1679663a7ea12ac168da84d2e8",
                    "language": "en-US",
                    "page": page,
                },
                timeout=20,
            )
            response.raise_for_status()
            break
        except requests.exceptions.RequestException as err:
            print(f"Attempt {attempt + 1} failed for page {page}: {err}")
            if attempt < max_retries - 1:
                time.sleep(2)
            else:
                print(f"Skipping page {page} after repeated failures.")

    if response is None or response.status_code != 200:
        continue

    page_results = response.json().get("results", [])
    if not page_results:
        break

    temp_df = pd.DataFrame(page_results)[
        ["id", "title", "overview", "release_date", "popularity", "vote_average", "vote_count"]
    ]
    all_pages.append(temp_df)

if all_pages:
    df = pd.concat(all_pages, ignore_index=True)
else:
    df = pd.DataFrame()

print(f"Loaded {len(all_pages)} pages")
df.head()

Loaded 428 pages

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,28.6090,9.048,312
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,68.9492,8.920,1967
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,59.5022,8.726,30798
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,134.6749,8.704,3601
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,28.5584,8.687,23184

In [12]:
df.shape

(8560, 7)